import type { Lesson } from './lessons';
import { ch, tc } from './lessons-everyday';

const x = (id: string, korean: string, english: string) => ({ id: `x.${id}`, korean, english });

/** Phase 3 continued: daily-life topics. */
export const DAILY: Lesson[] = [
  {
    id: '3.13',
    phase: 3,
    title: 'Family',
    ko: '가족',
    blurb: 'Who is who, and what to call them.',
    items: [
      x('가족', '가족', 'family'),
      x('엄마', '엄마', 'mom'),
      x('형', '형', 'older brother (said by a man)'),
      x('누나', '누나', 'older sister (said by a man)'),
      x('오빠', '오빠', 'older brother (said by a woman)'),
      x('언니', '언니', 'older sister (said by a woman)'),
      x('동생', '동생', 'younger sibling'),
      x('할머니', '할머니', 'grandmother'),
      x('할아버지', '할아버지', 'grandfather'),
      x('가족이몇명', '가족이 몇 명이에요?', 'How many people are in your family?'),
    ],
    steps: [
      tc(
        'The core family words',
        ['가족 means family. 엄마 and 아빠 are mom and dad. 할머니 and 할아버지 are grandmother and grandfather. 아들 is son and 딸 is daughter.', 'To ask about family size: 가족이 몇 명이에요? Answer with a native number + 명: 네 명이에요.'],
        'Ang 가족 ay pamilya. 엄마/아빠 = nanay/tatay. 할머니/할아버지 = lola/lolo. 가족이 몇 명이에요? = "Ilan kayo sa pamilya?" Sagot: 다섯 명이에요 (lima kami).',
        'Ang 몇 명 ay "ilang tao". Parehong pattern sa 3.3 sa restaurant: 몇 분이세요?',
        '엄마 at 아빠 ay halos kapareho ng "mama" at "papa". Madali.',
        [
          { ko: '가족', en: 'family', rom: 'gajok' },
          { ko: '엄마 / 아빠', en: 'mom / dad', rom: 'eomma / appa' },
          { ko: '할머니 / 할아버지', en: 'grandmother / grandfather', rom: 'halmeoni / harabeoji' },
          { ko: '가족이 몇 명이에요?', en: 'How many people are in your family?', rom: 'gajogi myeot myeongieyo' },
        ],
      ),
      tc(
        'Older siblings: it depends on who is speaking',
        ['Korean has different words for older siblings depending on the speaker. A man says 형 (older brother) and 누나 (older sister). A woman says 오빠 (older brother) and 언니 (older sister).', '동생 means younger sibling for everyone.'],
        'Parang "kuya" at "ate" sa Tagalog! 형/오빠 = kuya. 누나/언니 = ate. Pero depende kung lalaki o babae ang nagsasalita. 동생 = bunso/kapatid na mas bata.',
        'Gamitin ang 오빠 at 언니 kapag babae ka. Gamitin ang 형 at 누나 kapag lalaki ka. Maraming drama ang gumagamit nito kaya madali mong marinig.',
        'Lalaki → 형, 누나. Babae → 오빠, 언니. Isipin: "Kuya ng lalaki = hyung, kuya ng babae = oppa".',
        [
          { ko: '형', en: 'older brother (man says)', rom: 'hyeong' },
          { ko: '누나', en: 'older sister (man says)', rom: 'nuna' },
          { ko: '오빠', en: 'older brother (woman says)', rom: 'oppa' },
          { ko: '언니', en: 'older sister (woman says)', rom: 'eonni' },
          { ko: '동생', en: 'younger sibling', rom: 'dongsaeng' },
        ],
      ),
      ch('How do you ask "How many people are in your family?"', '가족이 몇 명이에요?', ['가족이 뭐예요?', '가족이 어디예요?'], '몇 명 = how many people.', '몇 명 = ilang tao.'),
      ch('You are a woman. What do you call your older brother?', '오빠', ['형', '누나'], 'Women say 오빠 for an older brother.', 'Babae → 오빠 (kuya).'),
      ch('You are a man. What do you call your older sister?', '누나', ['언니', '오빠'], 'Men say 누나 for an older sister.', 'Lalaki → 누나 (ate).'),
    ],
  },
  {
    id: '3.14',
    phase: 3,
    title: 'Likes and hobbies',
    ko: '좋아해요',
    blurb: 'Tell people what you love.',
    items: [
      x('좋아해요', '좋아해요', 'like'),
      x('싫어해요', '싫어해요', 'dislike'),
      x('취미가뭐예요', '취미가 뭐예요?', 'What is your hobby?'),
      x('음악을좋아해요', '음악을 좋아해요.', 'I like music.'),
      x('영화를좋아해요', '영화를 좋아해요.', 'I like movies.'),
      x('케이팝좋아해요', '케이팝을 좋아해요.', 'I like K-pop.'),
      x('요리해요', '요리해요.', 'I cook.'),
      x('운동해요', '운동해요.', 'I exercise.'),
    ],
    steps: [
      tc(
        'Object + 좋아해요',
        ['좋아해요 means "like" and takes an object: 음악을 좋아해요 ("I like music"). 싫어해요 is the opposite, "dislike".', 'Ask 취미가 뭐예요? ("what is your hobby?") to start a conversation.'],
        'Ang 좋아해요 ay "gusto ko" at ang 싫어해요 ay "ayaw ko / ayoko". Gumagamit ito ng 을/를 (2.2): 케이팝을 좋아해요 = "Gusto ko ang K-pop." 취미가 뭐예요? = "Ano ang hobby mo?"',
        'Ang 좋아요 (lesson 2.1) ay "maganda/okay". Ang 좋아해요 ay "gusto ko ang". Ang pagkakaiba ay maliit pero mahalaga: 좋아해요 laging may object.',
        '좋아해요 = 좋아 (good) + 해요 (do). Parang "gumagawa ng pagiging mabuti" = "gusto".',
        [
          { ko: '취미가 뭐예요?', en: 'What is your hobby?', rom: 'chwimiga mwoyeyo' },
          { ko: '음악을 좋아해요.', en: 'I like music.', rom: 'eumageul joahaeyo' },
          { ko: '케이팝을 좋아해요.', en: 'I like K-pop.', rom: 'keipabeul joahaeyo' },
          { ko: '매운 음식을 싫어해요.', en: 'I dislike spicy food.', rom: 'maeun eumsigeul sireohaeyo' },
        ],
      ),
      tc(
        'Hobbies you can do',
        ['Many hobbies are noun + 해요 (lesson 2.3): 요리해요 (I cook), 운동해요 (I exercise), 공부해요 (I study).', 'Others use a noun + 을/를 + verb: 영화를 봐요 (I watch movies).'],
        'Maraming hobby ay noun + 해요: 요리해요 (nagluluto), 운동해요 (nag-eehersisyo). Iba naman ay object + verb: 영화를 봐요 (nanonood ng pelikula).',
        'Idagdag ang 자주 (madalas) sa harap: 자주 요리해요 = "Madalas akong magluto."',
        '운동 = "undong" = "un-dong". Parang "undong" ay "movement". Isipin: "umaandar na".',
        [
          { ko: '요리해요.', en: 'I cook.', rom: 'yorihaeyo' },
          { ko: '운동해요.', en: 'I exercise.', rom: 'undonghaeyo' },
          { ko: '영화를 봐요.', en: 'I watch movies.', rom: 'yeonghwareul bwayo' },
        ],
      ),
      ch('How do you say "I like music"?', '음악을 좋아해요.', ['음악이 좋아요.', '음악을 먹어요.'], '음악 (music) + 을 + 좋아해요 (like).', '음악 + 을 + 좋아해요.'),
      ch('Which word means "dislike"?', '싫어해요', ['좋아해요', '괜찮아요'], '싫어해요 is the opposite of 좋아해요.', '싫어해요 = ayaw.'),
      ch('You want to ask about their hobby. What do you say?', '취미가 뭐예요?', ['취미를 먹어요?', '취미가 어디예요?'], '취미 = hobby.', '취미 = libangan.'),
    ],
  },
  {
    id: '3.15',
    phase: 3,
    title: 'Weather and seasons',
    ko: '날씨',
    blurb: 'The easiest small talk in any language.',
    items: [
      x('날씨어때요', '날씨가 어때요?', 'How is the weather?'),
      x('더워요', '더워요.', 'It is hot.'),
      x('추워요', '추워요.', 'It is cold.'),
      x('시원해요', '시원해요.', 'It is cool / refreshing.'),
      x('맑아요', '맑아요.', 'It is clear / sunny.'),
      x('비가와요', '비가 와요.', 'It is raining.'),
      x('눈이와요', '눈이 와요.', 'It is snowing.'),
      x('봄', '봄', 'spring'),
      x('여름', '여름', 'summer'),
      x('가을', '가을', 'autumn'),
      x('겨울', '겨울', 'winter'),
    ],
    steps: [
      tc(
        'How is the weather?',
        ['날씨가 어때요? means "how is the weather?". Common answers: 더워요 (hot), 추워요 (cold), 시원해요 (pleasantly cool), 맑아요 (clear).', '어때요? is the general "how is it?" question you can use for anything: 음식이 어때요? "How is the food?"'],
        'Ang 어때요? ay "Kumusta ito?" para sa kahit ano. 날씨가 어때요? = "Kumusta ang panahon?" Sagot: 더워요 (mainit), 추워요 (malamig), 맑아요 (maaliwalas).',
        'Ang 시원해요 ay hindi lang "cool". Ginagamit din ito sa mainit na sabaw o malamig na inumin na nakakagaan ng pakiramdam.',
        '더워요 at 추워요 ay magkaibang-magkaiba ang unang tunog: "d" at "ch". "Duh-wo-yo" mainit, "chu-wo-yo" malamig. Dalawang pantig lang ang kaibahan.',
        [
          { ko: '날씨가 어때요?', en: 'How is the weather?', rom: 'nalssiga eottaeyo' },
          { ko: '더워요.', en: 'It is hot.', rom: 'deowoyo' },
          { ko: '추워요.', en: 'It is cold.', rom: 'chuwoyo' },
          { ko: '시원해요.', en: 'It is cool.', rom: 'siwonhaeyo' },
          { ko: '맑아요.', en: 'It is clear.', rom: 'malgayo' },
        ],
      ),
      tc(
        'Rain, snow and seasons',
        ['In Korean, rain and snow "come": 비가 와요 (rain comes) and 눈이 와요 (snow comes). Use 이/가 (lesson 2.1) after 비 and 눈.', 'The four seasons: 봄 (spring), 여름 (summer), 가을 (autumn), 겨울 (winter).'],
        'Sa Korean, "dumarating" ang ulan at niyebe: 비가 와요 = "Umuulan." 눈이 와요 = "Nagyeyelo/Umuulan ng snow." Apat ang season nila: 봄, 여름, 가을, 겨울. Sa Pilipinas, dalawa lang: mainit at maulan!',
        'Ang 눈 ay may dalawang kahulugan: "snow" at "eye". Konteksto ang magsasabi. 눈이 와요 = snow, 눈이 아파요 = my eyes hurt.',
        'Ang 비 ay isang pantig lang, parang tunog ng patak: "bi". Maikli ang patak, maikli ang salita.',
        [
          { ko: '비가 와요.', en: 'It is raining.', rom: 'biga wayo' },
          { ko: '눈이 와요.', en: 'It is snowing.', rom: 'nuni wayo' },
          { ko: '봄 · 여름 · 가을 · 겨울', en: 'spring · summer · autumn · winter', rom: 'bom · yeoreum · gaeul · gyeoul' },
        ],
      ),
      ch('How do you ask about the weather?', '날씨가 어때요?', ['날씨가 뭐예요?', '날씨가 어디예요?'], '어때요 = how is it.', '어때요 = kumusta.'),
      ch('It is raining. What do you say?', '비가 와요.', ['눈이 와요.', '비가 맑아요.'], '비 = rain, 와요 = comes.', '비 = ulan, 와요 = dumarating.'),
      ch('Which word means "cold"?', '추워요', ['더워요', '시원해요'], '추워요 is cold, 더워요 is hot.', '추워요 = malamig.', { big: '추워요' }),
    ],
  },
  {
    id: '3.16',
    phase: 3,
    title: 'Colors and describing things',
    ko: '색깔과 형용사',
    blurb: 'Adjectives you will use every day.',
    items: [
      x('빨간색', '빨간색', 'red'),
      x('파란색', '파란색', 'blue'),
      x('노란색', '노란색', 'yellow'),
      x('하얀색', '하얀색', 'white'),
      x('검은색', '검은색', 'black'),
      x('초록색', '초록색', 'green'),
      x('커요', '커요', 'is big'),
      x('작아요', '작아요', 'is small'),
      x('예뻐요', '예뻐요', 'is pretty'),
      x('어려워요', '어려워요', 'is difficult'),
      x('쉬워요', '쉬워요', 'is easy'),
    ],
    steps: [
      tc(
        'Colors',
        ['Colors end in 색 (saek), meaning "color": 빨간색 (red), 파란색 (blue), 노란색 (yellow), 하얀색 (white), 검은색 (black), 초록색 (green).', 'The traditional Korean colors are blue, red, yellow, white and black. They are on this app.'],
        'Ang bawat kulay ay nagtatapos sa 색 = "kulay". 빨간색 = pula, 파란색 = asul, 노란색 = dilaw, 하얀색 = puti, 검은색 = itim, 초록색 = berde.',
        'Para sa mabilis na usapan, ginagamit lang ang unang bahagi: 빨강 (pula), 파랑 (asul), 노랑 (dilaw).',
        '색 = "saek" = "sak". Parang "kulay" ay "sak-ay". Maikli at madaling tandaan.',
        [
          { ko: '빨간색', en: 'red', rom: 'ppalgansaek' },
          { ko: '파란색', en: 'blue', rom: 'paransaek' },
          { ko: '노란색', en: 'yellow', rom: 'noransaek' },
          { ko: '하얀색', en: 'white', rom: 'hayansaek' },
          { ko: '검은색', en: 'black', rom: 'geomeunsaek' },
          { ko: '초록색', en: 'green', rom: 'choroksaek' },
        ],
      ),
      tc(
        'Adjectives work like verbs',
        ['Korean adjectives conjugate like verbs, so they use the same -아요 / -어요 ending: 작아요 (it is small), 커요 (it is big), 예뻐요 (it is pretty).', 'There is no "is" word. 이거 예뻐요 means "this is pretty".'],
        'Ang adjective ay parang verb: nagtatapos sa 아요/어요. Walang "ay" na kailangan. 이거 예뻐요 = "Maganda ito." 이거 커요 = "Malaki ito."',
        'Idagdag ang 너무 (sobra), 아주 (napaka), 조금 (medyo) sa harap: 너무 예뻐요 = "Sobrang ganda."',
        'Wala nang "is" o "ay" sa Korean. Ang dami nating "ay" sa English, pero hindi nila kailangan.',
        [
          { ko: '이거 예뻐요.', en: 'This is pretty.', rom: 'igeo yeppeoyo' },
          { ko: '너무 커요.', en: 'It is too big.', rom: 'neomu keoyo' },
          { ko: '한국어는 어려워요.', en: 'Korean is difficult.', rom: 'hangugeoneun eoryeowoyo' },
          { ko: '이거 쉬워요.', en: 'This is easy.', rom: 'igeo swiwoyo' },
        ],
      ),
      ch('Which word means "blue"?', '파란색', ['빨간색', '노란색'], '파란색 is blue.', '파란색 = asul.', { big: '파란색' }),
      ch('How do you say "It is too big"?', '너무 커요.', ['너무 작아요.', '너무 예뻐요.'], '커요 = big, 너무 = too.', '커요 = malaki, 너무 = sobra.'),
      ch('What does 이거 예뻐요 mean?', 'This is pretty.', ['This is expensive.', 'This is easy.'], '예쁘다 means pretty.', '예뻐요 = maganda.', { big: '이거 예뻐요' }),
    ],
  },
  {
    id: '3.17',
    phase: 3,
    title: 'Phone and messaging',
    ko: '전화와 문자',
    blurb: 'Answer calls, exchange numbers, and stay in touch.',
    items: [
      x('여보세요', '여보세요?', 'Hello? (on the phone)'),
      x('전화번호가뭐예요', '전화번호가 뭐예요?', 'What is your phone number?'),
      x('카카오톡있어요', '카카오톡 있어요?', 'Do you have KakaoTalk?'),
      x('문자보낼게요', '문자 보낼게요.', 'I will text you.'),
      x('나중에전화할게요', '나중에 전화할게요.', 'I will call you later.'),
      x('잘안들려요', '잘 안 들려요.', 'I cannot hear well.'),
    ],
    steps: [
      tc(
        'Picking up the phone',
        ['On the phone, say 여보세요? instead of 안녕하세요. To ask for a number: 전화번호가 뭐예요? Say the digits with Sino-Korean numbers (lesson 1.6).', 'KakaoTalk is the main messaging app in Korea. Ask 카카오톡 있어요? to swap contacts.'],
        'Ang "Hello?" sa telepono ay 여보세요?. Ang numero ng telepono ay gumagamit ng Sino-Korean (일, 이, 삼). Ang KakaoTalk ay parang Messenger ng Korea, kaya itanong ang 카카오톡 있어요?',
        'Ang 0 sa numero ay 공 (gong) o 영 (yeong). Sa telepono, karaniwan ang 공.',
        '여보세요 ay "yeo-bo-se-yo". Parang "Hello" na may apat na pantig. Isipin mong "ye-bo, seyo?".',
        [
          { ko: '여보세요?', en: 'Hello? (on the phone)', rom: 'yeoboseyo' },
          { ko: '전화번호가 뭐예요?', en: 'What is your phone number?', rom: 'jeonhwabeonhoga mwoyeyo' },
          { ko: '카카오톡 있어요?', en: 'Do you have KakaoTalk?', rom: 'kakaotok isseoyo' },
        ],
      ),
      tc(
        'Promising to do something',
        ['-(으)ㄹ게요 means "I will (do it for you / as promised)". 문자 보낼게요 is "I will text you". 나중에 전화할게요 is "I will call you later".', 'If you cannot hear: 잘 안 들려요 ("I cannot hear well"). Then 다시 한번 말해 주세요 from lesson 3.2.'],
        'Ang -ㄹ게요 ay "Gagawin ko na" bilang pangako. 문자 보낼게요 = "Magte-text ako." 나중에 전화할게요 = "Tatawag ako mamaya." Ang 잘 안 들려요 ay "Hindi ko marinig nang maayos."',
        'Ang 카드로 할게요 sa shopping (3.5) ay ganito rin: "Gagawin ko sa card."',
        '-ㄹ게요 ay "ll-ge-yo" = "I will, ge!" Parang "Sige, gagawin ko!"',
        [
          { ko: '문자 보낼게요.', en: 'I will text you.', rom: 'munja bonaelgeyo' },
          { ko: '나중에 전화할게요.', en: 'I will call you later.', rom: 'najunge jeonhwahalgeyo' },
          { ko: '잘 안 들려요.', en: 'I cannot hear well.', rom: 'jal an deullyeoyo' },
        ],
      ),
      ch('You answer your phone. What do you say?', '여보세요?', ['안녕히 가세요.', '계산해 주세요.'], '여보세요 is only used on the phone.', '여보세요 = hello sa phone.'),
      ch('You want to promise to call later. What do you say?', '나중에 전화할게요.', ['나중에 전화 있어요.', '나중에 전화예요.'], '-ㄹ게요 is for promises.', '-ㄹ게요 = pangako.'),
      ch('The line is bad. What do you say?', '잘 안 들려요.', ['잘 맛있어요.', '잘 갈아타요.'], '안 들려요 = cannot hear.', '안 들려요 = hindi marinig.'),
    ],
  },
  {
    id: '3.18',
    phase: 3,
    title: 'Taxi and getting around',
    ko: '택시와 이동',
    blurb: 'Tell a driver where to go and ask how far.',
    items: [
      x('택시', '택시', 'taxi'),
      x('여기로가주세요', '여기로 가 주세요.', 'Please go here.'),
      x('세워주세요', '여기서 세워 주세요.', 'Please stop here.'),
      x('얼마나걸려요', '얼마나 걸려요?', 'How long does it take?'),
      x('공항', '공항', 'airport'),
      x('가까워요', '가까워요.', 'It is near.'),
      x('멀어요', '멀어요.', 'It is far.'),
    ],
    steps: [
      tc(
        'Telling the driver',
        ['Show the address on your phone and say 여기로 가 주세요 ("please go here"). 로 means "toward / by". 가 주세요 is "please go".', 'To stop: 여기서 세워 주세요 ("please stop here").'],
        'Ipakita ang address sa phone at sabihin: 여기로 가 주세요 = "Pakipunta po dito." Para huminto: 여기서 세워 주세요 = "Pakihinto po dito." Ang 로 ay "papunta sa".',
        'Mag-save ng address sa Korean sa phone mo bago ka sumakay. Hindi lahat ng drayber ay nakakaintindi ng English.',
        '세워 = "sewo" = "i-set". "I-set dito" = "ihinto dito". Magkakatunog.',
        [
          { ko: '여기로 가 주세요.', en: 'Please go here.', rom: 'yeogiro ga juseyo' },
          { ko: '여기서 세워 주세요.', en: 'Please stop here.', rom: 'yeogiseo sewo juseyo' },
          { ko: '공항에 가 주세요.', en: 'Please go to the airport.', rom: 'gonghange ga juseyo' },
        ],
      ),
      tc(
        'How far, how long',
        ['얼마나 걸려요? means "how long does it take?". Answer with a number + 분 (minutes): 이십 분 걸려요 ("20 minutes").', '가까워요 means "it is near" and 멀어요 means "it is far".'],
        'Ang 얼마나 걸려요? ay "Gaano katagal?" Sagot: 이십 분 걸려요 = "Dalawampung minuto." 가까워요 = malapit, 멀어요 = malayo.',
        'Sa Korea, ang taxi ay may built-in na meter. Hindi mo kailangang makipagtawaran.',
        '멀어요 = "meo-reo-yo" = "mala-yo". Parang "malayo". Madali!',
        [
          { ko: '얼마나 걸려요?', en: 'How long does it take?', rom: 'eolmana geollyeoyo' },
          { ko: '이십 분 걸려요.', en: 'It takes 20 minutes.', rom: 'isip bun geollyeoyo' },
          { ko: '가까워요.', en: 'It is near.', rom: 'gakkawoyo' },
          { ko: '멀어요.', en: 'It is far.', rom: 'meoreoyo' },
        ],
      ),
      ch('You want to go to the airport. What do you say?', '공항에 가 주세요.', ['공항에서 세워요.', '공항이 있어요.'], '가 주세요 = please go.', '가 주세요 = pakipunta.'),
      ch('How do you ask "How long does it take?"', '얼마나 걸려요?', ['얼마예요?', '어디예요?'], '걸려요 = it takes (time).', '걸려요 = inaabot (oras).'),
      ch('Which means "It is far"?', '멀어요.', ['가까워요.', '비싸요.'], '멀어요 is far; 가까워요 is near.', '멀어요 = malayo.'),
    ],
  },
  {
    id: '3.19',
    phase: 3,
    title: 'Hotel and staying somewhere',
    ko: '호텔',
    blurb: 'Check in, ask for things, and sort out problems.',
    items: [
      x('예약했어요', '예약했어요.', 'I made a reservation.'),
      x('방있어요', '방 있어요?', 'Do you have a room?'),
      x('와이파이비밀번호', '와이파이 비밀번호가 뭐예요?', 'What is the Wi-Fi password?'),
      x('수건주세요', '수건 주세요.', 'A towel, please.'),
      x('체크아웃', '몇 시에 체크아웃이에요?', 'What time is check-out?'),
      x('에어컨이안돼요', '에어컨이 안 돼요.', 'The air conditioner does not work.'),
    ],
    steps: [
      tc(
        'Checking in',
        ['예약했어요 means "I made a reservation" (past tense, lesson 2.6). Add your name: 마리아예요. Ask 방 있어요? if you have no booking.', 'Many words are borrowed from English and written in Hangul: 체크인, 체크아웃, 와이파이, 에어컨.'],
        'Ang 예약했어요 ay "Nag-reserve ako." Pagkatapos, sabihin ang pangalan mo. 방 있어요? = "May kuwarto ba?" Maraming salita ay hiram sa English: 체크인, 와이파이, 에어컨.',
        'Dalhin ang passport. Hihingin ito sa karamihan ng hotel sa Korea.',
        '예약 = "yeyak" = "ye-yak". Parang "reserve" na may "ye" sa unahan. "Yes, reserve!"',
        [
          { ko: '예약했어요.', en: 'I made a reservation.', rom: 'yeyakhaesseoyo' },
          { ko: '방 있어요?', en: 'Do you have a room?', rom: 'bang isseoyo' },
          { ko: '몇 시에 체크아웃이에요?', en: 'What time is check-out?', rom: 'myeot sie chekeuausieyo' },
        ],
      ),
      tc(
        'Asking for things and reporting problems',
        ['Ask for items the same way as always: 수건 주세요 ("a towel, please"). Ask 와이파이 비밀번호가 뭐예요? for the Wi-Fi password.', 'Something is broken? Say 에어컨이 안 돼요 ("the air conditioner does not work"). 안 돼요 means "it does not work / not allowed".'],
        'Parehong pattern: 수건 주세요 = "Pakiabot po ng tuwalya." Para sa sira: 에어컨이 안 돼요 = "Hindi gumagana ang aircon." Ang 안 돼요 ay "hindi puwede / hindi gumagana".',
        'Ang 안 돼요 ay may dalawang gamit: "hindi gumagana" at "hindi puwede". Ginagamit mo ito sa maraming pagkakataon.',
        '비밀번호 ay "bi-mil-beon-ho" = "lihim na numero" = password. 비밀 = lihim.',
        [
          { ko: '수건 주세요.', en: 'A towel, please.', rom: 'sugeon juseyo' },
          { ko: '와이파이 비밀번호가 뭐예요?', en: 'What is the Wi-Fi password?', rom: 'waipai bimilbeonhoga mwoyeyo' },
          { ko: '에어컨이 안 돼요.', en: 'The air conditioner does not work.', rom: 'eeokeoni an dwaeyo' },
        ],
      ),
      ch('You have a booking. What do you say at check-in?', '예약했어요.', ['예약 있어요?', '예약 주세요.'], '예약했어요 = I reserved (past).', '예약했어요 = nag-reserve na ako.'),
      ch('You need the Wi-Fi password. What do you ask?', '와이파이 비밀번호가 뭐예요?', ['와이파이가 어디예요?', '와이파이 주세요?'], '비밀번호 = password.', '비밀번호 = password.'),
      ch('The aircon is broken. What do you say?', '에어컨이 안 돼요.', ['에어컨이 맛있어요.', '에어컨이 갈아타요.'], '안 돼요 = does not work.', '안 돼요 = hindi gumagana.'),
    ],
  },
  {
    id: '3.20',
    phase: 3,
    title: 'Clinic and pharmacy',
    ko: '병원과 약국',
    blurb: 'Describe what hurts and get help.',
    items: [
      x('머리', '머리', 'head'),
      x('배', '배', 'stomach'),
      x('목', '목', 'throat / neck'),
      x('머리가아파요', '머리가 아파요.', 'I have a headache.'),
      x('배가아파요', '배가 아파요.', 'I have a stomachache.'),
      x('열이있어요', '열이 있어요.', 'I have a fever.'),
      x('감기걸렸어요', '감기 걸렸어요.', 'I caught a cold.'),
      x('약국', '약국', 'pharmacy'),
      x('알레르기', '알레르기가 있어요.', 'I have an allergy.'),
    ],
    steps: [
      tc(
        'Body part + 이/가 아파요',
        ['아파요 (it hurts) comes after the body part with 이/가: 머리가 아파요 (my head hurts), 배가 아파요 (my stomach hurts), 목이 아파요 (my throat hurts).', 'Other useful phrases: 열이 있어요 (I have a fever), 감기 걸렸어요 (I caught a cold).'],
        'Ang pattern ay [bahagi ng katawan] + 이/가 + 아파요. 머리가 아파요 = "Masakit ang ulo ko." 배가 아파요 = "Masakit ang tiyan ko." 열이 있어요 = "May lagnat ako."',
        'Sa lugar na walang interpreter, ituro lang ang masakit na bahagi at sabihin ang 아파요.',
        '배 = tiyan, pero 배 ay "pear" at "ship" din. Konteksto ang tutukoy. Dito, 배가 아파요 = tiyan.',
        [
          { ko: '머리가 아파요.', en: 'I have a headache.', rom: 'meoriga apayo' },
          { ko: '배가 아파요.', en: 'I have a stomachache.', rom: 'baega apayo' },
          { ko: '열이 있어요.', en: 'I have a fever.', rom: 'yeori isseoyo' },
          { ko: '감기 걸렸어요.', en: 'I caught a cold.', rom: 'gamgi georyeosseoyo' },
        ],
      ),
      tc(
        'At the pharmacy and the doctor',
        ['약국 is a pharmacy and 병원 is a hospital or clinic. At a pharmacy say 감기약 주세요 ("cold medicine, please").', 'Always mention allergies: 알레르기가 있어요 ("I have an allergy").'],
        'Ang 약국 = botika, 병원 = ospital/klinika. 감기약 주세요 = "Pakiabot po ng gamot sa sipon." Sabihin ang 알레르기가 있어요 kung may allergy ka.',
        'Maraming pharmacy sa Korea ay nagbebenta ng gamot sa sakit ng ulo at sipon nang walang reseta.',
        '약 = "yak" = "gamot". Parang "yak" ay "yakap": gamot na parang yakap sa katawan.',
        [
          { ko: '약국', en: 'pharmacy', rom: 'yakguk' },
          { ko: '감기약 주세요.', en: 'Cold medicine, please.', rom: 'gamgiyak juseyo' },
          { ko: '알레르기가 있어요.', en: 'I have an allergy.', rom: 'allereugiga isseoyo' },
        ],
      ),
      ch('How do you say "I have a headache"?', '머리가 아파요.', ['머리가 맛있어요.', '머리를 아파요.'], '머리 (head) + 가 + 아파요.', '머리 + 가 + 아파요.'),
      ch('You have a fever. What do you say?', '열이 있어요.', ['열이 없어요.', '열이 맛있어요.'], '열 = fever, 있어요 = have.', '열 = lagnat, 있어요 = mayroon.'),
      ch('Where do you buy cold medicine?', '약국', ['공항', '카페'], '약국 is a pharmacy.', '약국 = botika.', { big: '약국' }),
    ],
  },
  {
    id: '3.21',
    phase: 3,
    title: 'Korean food',
    ko: '한국 음식',
    blurb: 'Dishes to order, and how to say what you cannot eat.',
    items: [
      x('비빔밥', '비빔밥', 'bibimbap (mixed rice)'),
      x('불고기', '불고기', 'bulgogi (marinated beef)'),
      x('삼겹살', '삼겹살', 'samgyeopsal (pork belly)'),
      x('치킨', '치킨', 'fried chicken'),
      x('라면', '라면', 'ramyeon (instant noodles)'),
      x('고기안먹어요', '고기 안 먹어요.', 'I do not eat meat.'),
      x('채식주의자', '채식주의자예요.', 'I am a vegetarian.'),
      x('땅콩알레르기', '땅콩 알레르기가 있어요.', 'I have a peanut allergy.'),
    ],
    steps: [
      tc(
        'Dishes you will see on every menu',
        ['비빔밥 (bibimbap) is rice mixed with vegetables. 불고기 (bulgogi) is marinated beef. 삼겹살 (samgyeopsal) is grilled pork belly. 치킨 is Korean fried chicken. 라면 is instant noodles.', 'Order with the pattern you already know: 비빔밥 하나 주세요.'],
        'Apat na pagkaing makikita mo kahit saan: 비빔밥 (halo-halong kanin), 불고기 (karne), 삼겹살 (liempo!), 치킨. 삼겹살 ay parang liempo na iniihaw sa mesa. 비빔밥 하나 주세요 = "Isang bibimbap po."',
        'Sa BBQ restaurant, minimum na dalawang order ang kailangan para sa karamihan ng karne.',
        '삼겹살 = "sam-gyeop-sal" = "tatlong-patong-laman" = liempo. Tatlong patong ng taba at karne.',
        [
          { ko: '비빔밥 하나 주세요.', en: 'One bibimbap, please.', rom: 'bibimbap hana juseyo' },
          { ko: '삼겹살 이 인분 주세요.', en: 'Two servings of pork belly, please.', rom: 'samgyeopsal i inbun juseyo' },
          { ko: '치킨', en: 'fried chicken', rom: 'chikin' },
          { ko: '라면', en: 'instant noodles', rom: 'ramyeon' },
        ],
      ),
      tc(
        'What you cannot or will not eat',
        ['안 먹어요 (lesson 2.4) says what you do not eat: 고기 안 먹어요. 채식주의자예요 means "I am a vegetarian". 땅콩 알레르기가 있어요 means "I have a peanut allergy".', 'Say it before ordering. Many dishes hide meat in the broth.'],
        'Para sa mga hindi kumakain ng karne: 고기 안 먹어요 o 채식주의자예요. Sabihin ito bago umorder, kasi maraming sabaw ay may karne o isda. Para sa allergy: 땅콩 알레르기가 있어요.',
        'Ang "고기" ay karne. Sa maraming Korean restaurant, kahit ang kimchi ay may fish sauce o hipon.',
        '고기 안 먹어요 = "hindi ako kumakain ng karne". Pamilyar ka na sa pattern: 안 + verb.',
        [
          { ko: '고기 안 먹어요.', en: 'I do not eat meat.', rom: 'gogi an meogeoyo' },
          { ko: '채식주의자예요.', en: 'I am a vegetarian.', rom: 'chaesikjuuijayeyo' },
          { ko: '땅콩 알레르기가 있어요.', en: 'I have a peanut allergy.', rom: 'ttangkong allereugiga isseoyo' },
        ],
      ),
      ch('Which dish is grilled pork belly?', '삼겹살', ['비빔밥', '라면'], '삼겹살 is pork belly.', '삼겹살 = liempo.', { big: '삼겹살' }),
      ch('You do not eat meat. What do you say?', '고기 안 먹어요.', ['고기 맛있어요.', '고기 주세요.'], '안 먹어요 = do not eat.', '안 먹어요 = hindi ako kumakain.'),
      ch('How do you order one bibimbap?', '비빔밥 하나 주세요.', ['비빔밥이에요.', '비빔밥 있어요.'], '하나 주세요 = one, please.', '하나 주세요 = isa po.'),
    ],
  },
  {
    id: '3.22',
    phase: 3,
    title: 'Feelings and compliments',
    ko: '감정과 칭찬',
    blurb: 'Say how you feel and say something kind.',
    items: [
      x('기뻐요', '기뻐요.', 'I am glad.'),
      x('슬퍼요', '슬퍼요.', 'I am sad.'),
      x('행복해요', '행복해요.', 'I am happy.'),
      x('무서워요', '무서워요.', 'I am scared.'),
      x('재미없어요', '재미없어요.', 'It is boring.'),
      x('멋있어요', '멋있어요.', 'You look cool.'),
      x('귀여워요', '귀여워요.', 'It is cute.'),
      x('최고예요', '최고예요!', 'You are the best!'),
    ],
    steps: [
      tc(
        'How you feel',
        ['Feelings are adjectives, so they use -아요 / -어요: 기뻐요 (glad), 슬퍼요 (sad), 행복해요 (happy), 무서워요 (scared).', '재미없어요 means "it is boring" and is the opposite of 재미있어요 (it is fun, lesson 3.10).'],
        'Parang adjective lang: 기뻐요 (masaya/natutuwa), 슬퍼요 (malungkot), 행복해요 (masaya, maligaya), 무서워요 (natatakot). 재미없어요 ay "nakakabagot" at ang kabaligtaran ay 재미있어요.',
        'Para sa mas malakas na damdamin, idagdag ang 너무: 너무 기뻐요 = "Sobrang saya ko."',
        '행복 ay "haengbok" = "saya at pagpapala". Parang "hang" at "bok": "hanggang bok-bok ang puso".',
        [
          { ko: '기뻐요.', en: 'I am glad.', rom: 'gippeoyo' },
          { ko: '슬퍼요.', en: 'I am sad.', rom: 'seulpeoyo' },
          { ko: '행복해요.', en: 'I am happy.', rom: 'haengbokhaeyo' },
          { ko: '재미없어요.', en: 'It is boring.', rom: 'jaemieopseoyo' },
        ],
      ),
      tc(
        'Compliments that land well',
        ['멋있어요 means "cool / stylish". 귀여워요 means "cute". 예뻐요 (lesson 3.16) means "pretty". 최고예요 means "you are the best".', 'A compliment is often returned with 감사합니다 or a shy 아니에요 ("no, not really").'],
        'Mga papuring magandang sabihin: 멋있어요 (astig), 귀여워요 (cute), 예뻐요 (maganda), 최고예요 (the best!). Madalas ang sagot ay 감사합니다 o mahiyain na 아니에요 = "Naku, hindi naman."',
        'Ang 귀여워요 ay ginagamit para sa mga bata, hayop, at maging sa mga kaibigan. Hindi ito nakakainsulto.',
        '최고 = "choego" = "ang pinakamataas". "Cho-ego" = "ang pinaka-ego". Ang pinakamataas.',
        [
          { ko: '멋있어요.', en: 'You look cool.', rom: 'meosisseoyo' },
          { ko: '귀여워요.', en: 'It is cute.', rom: 'gwiyeowoyo' },
          { ko: '최고예요!', en: 'You are the best!', rom: 'choegoyeyo' },
        ],
      ),
      ch('Which word means "I am sad"?', '슬퍼요.', ['기뻐요.', '행복해요.'], '슬퍼요 is sad.', '슬퍼요 = malungkot.'),
      ch('You see a puppy. What do you say?', '귀여워요!', ['무서워요!', '재미없어요!'], '귀엽다 means cute.', '귀여워요 = cute.'),
      ch('What does 재미없어요 mean?', 'It is boring.', ['It is fun.', 'It is cute.'], '없어요 makes it the opposite of 재미있어요.', '없어요 = kabaligtaran ng 있어요.', { big: '재미없어요' }),
    ],
  },
];

/** Phase 4: grammar beyond the basics. */
export const LEVELUP: Lesson[] = [
  {
    id: '4.1',
    phase: 4,
    title: 'Polite commands: -(으)세요',
    ko: '-(으)세요',
    blurb: 'The respectful way to say "please do".',
    items: [
      x('어서오세요', '어서 오세요.', 'Welcome.'),
      x('앉으세요', '앉으세요.', 'Please sit.'),
      x('가세요', '가세요.', 'Please go.'),
      x('드세요', '드세요.', 'Please eat.'),
      x('어디가세요', '어디 가세요?', 'Where are you going? (respectful)'),
    ],
    steps: [
      tc(
        'Vowel stem + 세요, consonant stem + 으세요',
        ['Add 세요 to a vowel stem and 으세요 to a consonant stem. 가다 → 가세요. 앉다 → 앉으세요. 읽다 → 읽으세요.', 'It makes polite commands and also respectful questions to or about someone you respect: 어디 가세요? "Where are you going?"'],
        'Ang -(으)세요 ay magalang na utos at tanong. Vowel stem + 세요: 가세요. Consonant stem + 으세요: 앉으세요. Ito ang "po" ng Korean verb: 어디 가세요? = "Saan po kayo pupunta?"',
        'Narinig mo na ito: 안녕히 가세요 (3.3 at 1.1) ay 가세요. Nasa 어서 오세요 din (welcome).',
        'Ang 세요 ay "po". Idagdag mo ang "po" sa verb, at magalang na. Gaya ng "Kain po" = 드세요.',
        [
          { ko: '어서 오세요.', en: 'Welcome.', rom: 'eoseo oseyo' },
          { ko: '앉으세요.', en: 'Please sit.', rom: 'anjeuseyo' },
          { ko: '가세요.', en: 'Please go.', rom: 'gaseyo' },
          { ko: '어디 가세요?', en: 'Where are you going?', rom: 'eodi gaseyo' },
        ],
      ),
      tc(
        'A special verb: 드세요',
        ['For eating, the respectful form is 드세요, not 먹으세요. 맛있게 드세요 (lesson 3.12) uses it.', 'Respect for the listener changes some common verbs. 먹다 becomes 드시다 for someone you respect.'],
        'Para sa pagkain, mas magalang ang 드세요 kaysa 먹으세요. Kaya ang 맛있게 드세요 ay "Kain po kayo nang masarap." May ilang verb na may espesyal na magalang na anyo.',
        'Hindi mo kailangang gamitin ang 드시다 para sa sarili. Para lang ito sa taong iginagalang mo.',
        '드 = "deu" = "dalhin ang pagkain sa bibig". Isipin: "Deu! Kain na!"',
        [
          { ko: '드세요.', en: 'Please eat.', rom: 'deuseyo' },
          { ko: '맛있게 드세요.', en: 'Enjoy your meal.', rom: 'masitge deuseyo' },
        ],
      ),
      ch('Make "please sit" from 앉다 (consonant stem).', '앉으세요', ['앉세요', '앉아세요'], 'Consonant stem + 으세요.', 'May batchim → 으세요.'),
      ch('Make "please go" from 가다 (vowel stem).', '가세요', ['가으세요', '가아요'], 'Vowel stem + 세요.', 'Walang batchim → 세요.'),
      ch('What does 어디 가세요? ask?', 'Where are you going? (respectful)', ['Where is it?', 'What do you eat?'], '어디 = where, 가세요 = go (respectful).', '어디 가세요 = saan po kayo pupunta.'),
    ],
  },
  {
    id: '4.2',
    phase: 4,
    title: 'Do it for me: -아/어 주세요',
    ko: '-아/어 주세요',
    blurb: 'Ask someone to do something.',
    items: [
      x('도와주세요', '도와 주세요.', 'Please help me.'),
      x('말해주세요', '말해 주세요.', 'Please say it / tell me.'),
      x('가르쳐주세요', '가르쳐 주세요.', 'Please teach me.'),
      x('기다려주세요', '기다려 주세요.', 'Please wait.'),
      x('사진찍어주세요', '사진 찍어 주세요.', 'Please take a picture.'),
    ],
    steps: [
      tc(
        'Verb + 아/어 + 주세요',
        ['Take the 아/어 form of a verb (lesson 2.3) and add 주세요: 기다리다 → 기다려 주세요 (please wait). 가르치다 → 가르쳐 주세요 (please teach me). 말하다 → 말해 주세요.', 'It literally means "do it and give it to me", so it is the polite way to ask for a favor.'],
        'Ito ang "Pakiusap po" ng Korean. Verb sa 아/어 form + 주세요: 기다려 주세요 = "Pakihintay po." 가르쳐 주세요 = "Pakituro po." 도와 주세요 = "Pakitulungan po."',
        'Ang 도와 주세요 (3.11) ay nagmula rin dito. Ngayon, alam mo na ang tunay na pattern sa likod nito.',
        '주세요 = "bigay po". Verb + 주세요 = "Pakigawa po". Parang "paki-" ng Tagalog.',
        [
          { ko: '기다려 주세요.', en: 'Please wait.', rom: 'gidaryeo juseyo' },
          { ko: '가르쳐 주세요.', en: 'Please teach me.', rom: 'gareuchyeo juseyo' },
          { ko: '도와 주세요.', en: 'Please help me.', rom: 'dowa juseyo' },
        ],
      ),
      tc(
        'Everyday requests',
        ['Photos: 사진 찍어 주세요 ("please take a picture"). Repeating: 다시 말해 주세요. Slow down: 천천히 말해 주세요 (lesson 3.2).', 'Always add a polite 감사합니다 afterwards.'],
        'Mga madalas gamitin: 사진 찍어 주세요 = "Pakikuha po ng litrato." 다시 말해 주세요 = "Pakiulit po." 천천히 말해 주세요 = "Pakibagalan po."',
        'Kapag magpapakuha ng litrato, ibigay ang phone at sabihin 사진 찍어 주세요. Mabait ang karamihan ng Koreano.',
        '찍어 = "jjigeo" = "tsik!" Parang tunog ng camera: "tsik!" = kuha ng litrato.',
        [
          { ko: '사진 찍어 주세요.', en: 'Please take a picture.', rom: 'sajin jjigeo juseyo' },
          { ko: '다시 말해 주세요.', en: 'Please say it again.', rom: 'dasi malhae juseyo' },
        ],
      ),
      ch('How do you say "Please wait"?', '기다려 주세요.', ['기다려요.', '기다리고 싶어요.'], '기다려 + 주세요.', '기다려 + 주세요 = pakihintay.'),
      ch('You want a photo taken. What do you say?', '사진 찍어 주세요.', ['사진 찍고 싶어요.', '사진이 있어요.'], '찍어 주세요 = please take.', '찍어 주세요 = pakikuha.'),
      ch('What does 가르쳐 주세요 mean?', 'Please teach me.', ['Please wait.', 'Please go.'], '가르치다 means to teach.', '가르치다 = magturo.', { big: '가르쳐 주세요' }),
    ],
  },
  {
    id: '4.3',
    phase: 4,
    title: 'Because: -아서/어서',
    ko: '-아서/어서',
    blurb: 'Give a reason.',
    items: [
      x('피곤해서', '피곤해서 집에 가요.', 'I am tired, so I go home.'),
      x('비가와서', '비가 와서 안 가요.', 'It is raining, so I am not going.'),
      x('맛있어서', '맛있어서 많이 먹어요.', 'It is tasty, so I eat a lot.'),
      x('좋아서', '날씨가 좋아서 기분이 좋아요.', 'The weather is nice, so I feel good.'),
    ],
    steps: [
      tc(
        'Reason first, result second',
        ['Attach 아서 or 어서 to the stem using the same bright/dark rule as -아요/-어요: 피곤하다 → 피곤해서, 오다 → 와서, 맛있다 → 맛있어서.', 'The reason comes first, then the result: 피곤해서 집에 가요 ("because I am tired, I go home").'],
        'Ang -아서/어서 ay "dahil" o "kaya". Parehong rule sa -아요/어요. Una ang dahilan, pangalawa ang resulta: 피곤해서 집에 가요 = "Pagod ako, kaya uuwi ako."',
        'Hindi ka maglalagay ng 았/었 sa unahan ng 아서/어서. Ang panahon ay nasa huling verb lang.',
        '-아서 ay "aseo" = "ayy, kaya". Parang "kaya nga" ng Tagalog. Dahilan muna, resulta pagkatapos.',
        [
          { ko: '피곤해서 집에 가요.', en: 'I am tired, so I go home.', rom: 'pigonhaeseo jibe gayo' },
          { ko: '비가 와서 안 가요.', en: 'It is raining, so I am not going.', rom: 'biga waseo an gayo' },
          { ko: '맛있어서 많이 먹어요.', en: 'It is tasty, so I eat a lot.', rom: 'masisseoseo mani meogeoyo' },
        ],
      ),
      tc(
        'A limit to remember',
        ['You cannot use 주세요 or 볼까요 in the second part after -아서/어서. Do not say "because it is cold, please close the door" with this form. Use -(으)니까 for that, which you will learn later.', 'Use -아서/어서 for natural reasons and feelings.'],
        'Hindi puwedeng gamitin ang 주세요 o 볼까요 sa pangalawang bahagi pagkatapos ng -아서/어서. Para sa utos o mungkahi, iba ang gamit (-(으)니까, sa susunod na lesson). Gamitin ito para sa natural na dahilan at damdamin.',
        'Kung may duda, ihambing: "Pagod ako, kaya uuwi ako" okay. "Pagod ako, kaya umuwi ka na" iba ang gramatika.',
        'Dahilan + natural na resulta = 아서/어서. Dahilan + utos = ibang anyo.',
        [
          { ko: '날씨가 좋아서 기분이 좋아요.', en: 'The weather is nice, so I feel good.', rom: 'nalssiga joaseo gibuni joayo' },
        ],
      ),
      ch('Make "because it is tasty" from 맛있다.', '맛있어서', ['맛있아서', '맛있고서'], 'ㅣ is dark, so 어서.', 'Dark vowel → 어서.'),
      ch('Make "because it is raining" from 비가 오다.', '비가 와서', ['비가 오어서', '비가 오아서'], '오 + 아서 contracts to 와서.', '오 + 아서 = 와서.'),
      ch('Which sentence says "I am tired, so I go home"?', '피곤해서 집에 가요.', ['집에 가서 피곤해요.', '피곤하고 집에 가요.'], 'Reason first, result second.', 'Dahilan muna, resulta pangalawa.'),
    ],
  },
  {
    id: '4.4',
    phase: 4,
    title: 'But: -지만',
    ko: '-지만',
    blurb: 'Contrast two ideas.',
    items: [
      x('맛있지만매워요', '맛있지만 매워요.', 'It is tasty but spicy.'),
      x('비싸지만좋아요', '비싸지만 좋아요.', 'It is expensive but good.'),
      x('어렵지만재미있어요', '한국어는 어렵지만 재미있어요.', 'Korean is hard but fun.'),
    ],
    steps: [
      tc(
        'Stem + 지만',
        ['Add 지만 directly to the stem. No vowel rules, no contractions. 맛있다 → 맛있지만, 비싸다 → 비싸지만, 어렵다 → 어렵지만.', 'The result is the contrast: 맛있지만 매워요 ("it is tasty but spicy").'],
        'Ang -지만 ay "pero" at ito ang pinakamadali. Stem + 지만, wala nang iba. 맛있지만 매워요 = "Masarap pero maanghang." 비싸지만 좋아요 = "Mahal pero maganda."',
        'Ito ay mas natural kaysa sa 그런데 sa loob ng isang pangungusap. Gamitin ang 그런데 para sa dalawang magkahiwalay na pangungusap.',
        '지만 = "jiman" = "pero ji-man". Parang "pero, jiman!" "Pero, hanggang doon lang."',
        [
          { ko: '맛있지만 매워요.', en: 'It is tasty but spicy.', rom: 'masitjiman maewoyo' },
          { ko: '비싸지만 좋아요.', en: 'It is expensive but good.', rom: 'bissajiman joayo' },
          { ko: '한국어는 어렵지만 재미있어요.', en: 'Korean is hard but fun.', rom: 'hangugeoneun eoryeopjiman jaemiisseoyo' },
        ],
      ),
      ch('Make "but it is expensive" from 비싸다.', '비싸지만', ['비싸아서', '비싸고'], 'Stem 비싸 + 지만.', 'Stem + 지만.'),
      ch('Which sentence says "It is tasty but spicy"?', '맛있지만 매워요.', ['맛있어서 매워요.', '맛있고 매워요.'], '지만 = but.', '지만 = pero.'),
      ch('What does 어렵지만 재미있어요 mean?', 'It is hard but fun.', ['It is hard, so it is fun.', 'It is easy and fun.'], '어렵다 = hard, 지만 = but.', '어렵다 = mahirap, 지만 = pero.', { big: '어렵지만 재미있어요' }),
    ],
  },
  {
    id: '4.5',
    phase: 4,
    title: 'If: -(으)면',
    ko: '-(으)면',
    blurb: 'Talk about conditions.',
    items: [
      x('시간있으면', '시간 있으면 같이 가요.', 'If you have time, let us go together.'),
      x('비가오면', '비가 오면 집에 있어요.', 'If it rains, I stay home.'),
      x('피곤하면', '피곤하면 쉬어요.', 'If you are tired, rest.'),
    ],
    steps: [
      tc(
        'Vowel stem + 면, consonant stem + 으면',
        ['Add 면 to a vowel stem and 으면 to a consonant stem: 오다 → 오면, 하다 → 하면, 있다 → 있으면, 먹다 → 먹으면.', '시간 있으면 같이 가요 means "if you have time, let us go together".'],
        'Ang -(으)면 ay "kung/kapag". Vowel stem + 면, consonant stem + 으면. 비가 오면 집에 있어요 = "Kapag umuulan, nasa bahay lang ako." 시간 있으면 같이 가요 = "Kung may oras ka, sabay tayo."',
        'Parehong rule sa -(으)ㄹ 거예요, pero hindi ㄹ ang idinadagdag, kundi 면.',
        '면 = "myeon" = "kapag mo-yon". Parang "kapag meron, yon!"',
        [
          { ko: '비가 오면 집에 있어요.', en: 'If it rains, I stay home.', rom: 'biga omyeon jibe isseoyo' },
          { ko: '시간 있으면 같이 가요.', en: 'If you have time, let us go together.', rom: 'sigan isseumyeon gachi gayo' },
          { ko: '피곤하면 쉬어요.', en: 'If you are tired, rest.', rom: 'pigonhamyeon swieoyo' },
        ],
      ),
      ch('Make "if it comes" from 오다 (vowel stem).', '오면', ['오으면', '와면'], 'Vowel stem + 면.', 'Walang batchim → 면.'),
      ch('Make "if you have" from 있다 (consonant stem).', '있으면', ['있면', '있어면'], 'Consonant stem + 으면.', 'May batchim → 으면.'),
      ch('What does 피곤하면 쉬어요 mean?', 'If you are tired, rest.', ['I rested because I was tired.', 'I am tired but I rest.'], '면 = if.', '면 = kung/kapag.', { big: '피곤하면 쉬어요' }),
    ],
  },
  {
    id: '4.6',
    phase: 4,
    title: 'Question words',
    ko: '의문사',
    blurb: 'Who, what, when, where, why, how.',
    items: [
      x('누구', '누구', 'who'),
      x('뭐', '뭐', 'what'),
      x('언제', '언제', 'when'),
      x('어디', '어디', 'where'),
      x('왜', '왜', 'why'),
      x('어떻게', '어떻게', 'how'),
      x('몇', '몇', 'how many'),
      x('왜요', '왜요?', 'Why? (polite)'),
    ],
    steps: [
      tc(
        'The seven question words',
        ['누구 (who), 뭐 (what), 언제 (when), 어디 (where), 왜 (why), 어떻게 (how), 몇 (how many). They sit where the answer would be, not at the start like in English.', 'To ask "why?" alone, say 왜요? To ask "how is it?", say 어때요?.'],
        'Pitong tanong: 누구 (sino), 뭐 (ano), 언제 (kailan), 어디 (saan), 왜 (bakit), 어떻게 (paano), 몇 (ilan). Hindi sila nasa unahan ng pangungusap, kundi nasa lugar ng sagot, parang sa Tagalog: "Ikaw ay nasaan?"',
        'Walang pagbabago sa word order. Palitan lang ang sagot ng question word: 내일 만나요 → 언제 만나요?',
        'Pitong tanong: sino, ano, kailan, saan, bakit, paano, ilan. Gumawa ng kanta: nu-gu, mwo, eon-je, eo-di, wae, eot-tteo-ke, myeot.',
        [
          { ko: '누구예요?', en: 'Who is it?', rom: 'nuguyeyo' },
          { ko: '언제 만나요?', en: 'When do we meet?', rom: 'eonje mannayo' },
          { ko: '어디 가요?', en: 'Where are you going?', rom: 'eodi gayo' },
          { ko: '왜요?', en: 'Why?', rom: 'waeyo' },
          { ko: '어떻게 가요?', en: 'How do I get there?', rom: 'eotteoke gayo' },
        ],
      ),
      tc(
        'Questions in action',
        ['Statements become questions by changing the question word and lifting the tone: 친구를 만나요 → 누구를 만나요? "Who are you meeting?"', 'Combine them: 언제 어디에서 만나요? "When and where do we meet?"'],
        'Mula sa pangungusap, palitan ang bahagi ng question word at itaas ang tono. 친구를 만나요 → 누구를 만나요? Pagsamahin: 언제 어디에서 만나요? = "Kailan at saan tayo magkikita?"',
        'Sa pang-araw-araw, ang 뭐 ay mas karaniwan kaysa 무엇. Pareho ang kahulugan.',
        'Ang sagot ang papalit sa question word. Isipin ang tanong na parang pangungusap na may butas.',
        [
          { ko: '누구를 만나요?', en: 'Who are you meeting?', rom: 'nugureul mannayo' },
          { ko: '언제 어디에서 만나요?', en: 'When and where do we meet?', rom: 'eonje eodieseo mannayo' },
        ],
      ),
      ch('Which word means "why"?', '왜', ['뭐', '누구'], '왜 is why.', '왜 = bakit.', { big: '왜' }),
      ch('Ask "When do we meet?"', '언제 만나요?', ['어디 만나요?', '누구 만나요?'], '언제 = when.', '언제 = kailan.'),
      ch('Ask "Where are you going?"', '어디 가요?', ['언제 가요?', '왜 가요?'], '어디 = where.', '어디 = saan.'),
    ],
  },
  {
    id: '4.7',
    phase: 4,
    title: 'Adverbs that sound natural',
    ko: '부사',
    blurb: 'Small words that make you sound fluent.',
    items: [
      x('항상', '항상', 'always'),
      x('자주', '자주', 'often'),
      x('가끔', '가끔', 'sometimes'),
      x('보통', '보통', 'usually'),
      x('아주', '아주', 'very'),
      x('조금', '조금', 'a little'),
      x('너무', '너무', 'too / so'),
      x('같이', '같이', 'together'),
      x('혼자', '혼자', 'alone'),
    ],
    steps: [
      tc(
        'How often',
        ['항상 (always), 자주 (often), 보통 (usually), 가끔 (sometimes). Put them before the verb: 자주 커피를 마셔요 ("I often drink coffee").', 'To say never, use 안 (lesson 2.4) with 전혀: 전혀 안 먹어요 ("I never eat").'],
        'Mga salitang pang-dalas: 항상 (palagi), 자주 (madalas), 보통 (karaniwan), 가끔 (paminsan-minsan). Ilagay sa harap ng verb: 자주 커피를 마셔요 = "Madalas akong uminom ng kape."',
        'Ang 가끔 ay maiksi pero mahalaga. Sagot ito sa tanong na "Gaano kadalas?"',
        '자주 = "jaju" = "ja-ju" = "madalas ju-go". Isipin: "Ja-ju! Palagi!"',
        [
          { ko: '항상', en: 'always', rom: 'hangsang' },
          { ko: '자주', en: 'often', rom: 'jaju' },
          { ko: '보통', en: 'usually', rom: 'botong' },
          { ko: '가끔', en: 'sometimes', rom: 'gakkeum' },
        ],
      ),
      tc(
        'How much, and with whom',
        ['아주 (very), 너무 (too / so), 조금 (a little) say how much. 같이 (together) and 혼자 (alone) say with whom.', '혼자 살아요 means "I live alone". 같이 먹어요 means "let us eat together".'],
        'Mga salitang pang-dami: 아주 (napaka), 너무 (sobra), 조금 (kaunti). Pang-kasama: 같이 (sabay-sabay), 혼자 (mag-isa). 혼자 살아요 = "Mag-isa akong nakatira."',
        'Ang 너무 sa Korean ay madalas positibo rin: 너무 좋아요 = "Sobrang ganda/sarap." Hindi ito laging "sobra na".',
        '혼자 = "honja" = "hon-ja" = "ako lang". "Hon-ja" at "ako lang" ay magkapareho ng ritmo.',
        [
          { ko: '아주 맛있어요.', en: 'It is very tasty.', rom: 'aju masisseoyo' },
          { ko: '조금 어려워요.', en: 'It is a little difficult.', rom: 'jogeum eoryeowoyo' },
          { ko: '같이 먹어요.', en: 'Let us eat together.', rom: 'gachi meogeoyo' },
          { ko: '혼자 살아요.', en: 'I live alone.', rom: 'honja sarayo' },
        ],
      ),
      ch('Which word means "often"?', '자주', ['가끔', '항상'], '자주 means often.', '자주 = madalas.', { big: '자주' }),
      ch('How do you say "It is very tasty"?', '아주 맛있어요.', ['조금 맛있어요.', '같이 맛있어요.'], '아주 = very.', '아주 = napaka.'),
      ch('You want to say "I live alone."', '혼자 살아요.', ['같이 살아요.', '자주 살아요.'], '혼자 = alone.', '혼자 = mag-isa.'),
    ],
  },
];
