import type { Lesson } from './lessons';

export const MORE2: Lesson[] = [
  {
    id: '1.4',
    phase: 1,
    title: 'This, that, over there',
    ko: '이 / 그 / 저',
    blurb: 'Pointing at things and asking what they are.',
    items: [
      { id: 'w.이거', korean: '이거', english: 'this (thing)' },
      { id: 'w.그거', korean: '그거', english: 'that (thing near you)' },
      { id: 'w.저거', korean: '저거', english: 'that (thing over there)' },
      { id: 'w.뭐', korean: '뭐', english: 'what' },
      { id: 's.이거뭐예요', korean: '이거 뭐예요?', english: 'What is this?' },
    ],
    steps: [
      {
        kind: 'teach',
        title: 'Three distances',
        body: [
          'Korean has three words for "that", based on who is near the thing. 이 is near me, 그 is near you (or already mentioned), 저 is far from both of us.',
          'Add 거 ("thing") and you get 이거, 그거, 저거: this, that, that over there.',
        ],
        tl: ['Tatlo ang "iyon" sa Korean. 이 = ito (malapit sa akin). 그 = iyan (malapit sa iyo). 저 = iyon (malayo sa ating dalawa). Parehong-pareho sa Tagalog: ito, iyan, iyon!'],
        tip: 'Alam mo na ang ganitong sistema dahil Tagalog ka. Ito / iyan / iyon = 이 / 그 / 저. Hindi ito mahirap para sa iyo.',
        remember: '이 (i) = ito, 그 (geu) = iyan, 저 (jeo) = iyon. Magkapareho ang pagkakasunod-sunod sa Tagalog.',
        phrases: [
          { ko: '이거', en: 'this (near me)', rom: 'igeo' },
          { ko: '그거', en: 'that (near you)', rom: 'geugeo' },
          { ko: '저거', en: 'that over there', rom: 'jeogeo' },
        ],
      },
      {
        kind: 'teach',
        title: 'What is this?',
        body: [
          '뭐 means "what". Put it at the end with 예요: 뭐예요? Combine with 이거: 이거 뭐예요? "What is this?"',
          'You answer with the noun plus 이에요 / 예요, as in lesson 1.2.',
        ],
        tl: ['Ang "ano" ay 뭐. 이거 뭐예요? = "Ano ito?" Sagot: 커피예요 = "Kape po."'],
        tip: 'Para magtanong, itaas lang ang tono sa dulo. Walang kailangang baguhin sa salita.',
        remember: '뭐 ay "mwo". Isipin mong "mwah?" na may pagtataka: "ano?"',
        phrases: [
          { ko: '이거 뭐예요?', en: 'What is this?', rom: 'igeo mwoyeyo' },
          { ko: '커피예요.', en: 'It is coffee.', rom: 'keopi-yeyo' },
          { ko: '저거 뭐예요?', en: 'What is that over there?', rom: 'jeogeo mwoyeyo' },
        ],
      },
      {
        kind: 'choice',
        prompt: 'Something is right next to the person you are talking to. Which word?',
        options: ['이거', '그거', '저거'],
        answer: '그거',
        why: '그 is for things near the listener.',
        whyTl: 'Malapit sa kausap mo, kaya 그거 (iyan).',
      },
      {
        kind: 'choice',
        prompt: 'How do you ask "What is this?"',
        options: ['이거 뭐예요?', '이거 학생이에요?', '뭐 이거예요?'],
        answer: '이거 뭐예요?',
        why: '이거 (this) + 뭐예요 (what is it).',
        whyTl: '이거 (ito) + 뭐예요 (ano?). Ang sagot ay laging nasa dulo ng pangungusap.',
      },
      {
        kind: 'choice',
        prompt: 'What does 저거 mean?',
        big: '저거',
        options: ['that over there', 'this', 'what'],
        answer: 'that over there',
        why: '저 is for things far from both of you.',
        whyTl: 'Ang 저 ay malayo sa inyong dalawa: iyon.',
      },
    ],
  },
  {
    id: '1.5',
    phase: 1,
    title: 'Have and do not have',
    ko: '있어요 / 없어요',
    blurb: 'One verb for "there is", one for "there is not".',
    items: [
      { id: 'w.있어요', korean: '있어요', english: 'there is / I have' },
      { id: 'w.없어요', korean: '없어요', english: 'there is not / I do not have' },
      { id: 'w.시간', korean: '시간', english: 'time' },
      { id: 'w.돈', korean: '돈', english: 'money' },
      { id: 'w.친구', korean: '친구', english: 'friend' },
      { id: 's.시간있어요', korean: '시간 있어요?', english: 'Do you have time?' },
    ],
    steps: [
      {
        kind: 'teach',
        title: 'Exists or does not exist',
        body: [
          '있어요 means "there is" or "I have". 없어요 means "there is not" or "I do not have". They are opposites, so learn them as a pair.',
          'Korean does not say "I have a friend". It says something closer to "friend exists": 친구 있어요.',
        ],
        tl: ['Ito ang "may" at "wala" sa Tagalog! 있어요 = may. 없어요 = wala. Perfect na magkapareho ang gamit.'],
        tip: 'Hindi mo kailangan ng "ako" o "ikaw". 시간 있어요? ay "May oras ka ba?" na.',
        remember: '있 ay may dalawang ㅅ na parang dalawang tao na nagkikita. 없 ay may ㅂ + ㅅ na parang may nawala sa pagitan.',
        phrases: [
          { ko: '있어요', en: 'there is / I have', rom: 'isseoyo' },
          { ko: '없어요', en: 'there is not / I do not have', rom: 'eopseoyo' },
        ],
      },
      {
        kind: 'teach',
        title: 'Useful nouns',
        body: ['Put a noun in front, and you can ask or answer about almost anything.'],
        tl: ['Ilagay ang noun sa harap. Tanong: 시간 있어요? (May oras ka?). Sagot: 네, 있어요 (Opo, meron) o 아니요, 없어요 (Hindi, wala).'],
        tip: 'Ang tanong at sagot ay iisa ang salita. Ulitin mo lang ang verb: 있어요? → 있어요.',
        remember: 'Sagutin ang tanong gamit ang verb: 있어요? 네, 있어요. Parang "Meron? Meron."',
        phrases: [
          { ko: '시간 있어요?', en: 'Do you have time?', rom: 'sigan isseoyo' },
          { ko: '돈 없어요.', en: 'I have no money.', rom: 'don eopseoyo' },
          { ko: '친구 있어요.', en: 'I have a friend.', rom: 'chingu isseoyo' },
        ],
      },
      {
        kind: 'choice',
        prompt: 'What does 돈 없어요 mean?',
        big: '돈 없어요',
        options: ['I have no money.', 'I have money.', 'Where is the money?'],
        answer: 'I have no money.',
        why: '돈 = money, 없어요 = there is not.',
        whyTl: '돈 = pera, 없어요 = wala. "Wala akong pera."',
      },
      {
        kind: 'choice',
        prompt: 'How do you ask "Do you have time?"',
        options: ['시간 있어요?', '시간 없어요', '시간이에요?'],
        answer: '시간 있어요?',
        why: '시간 (time) + 있어요 (there is).',
        whyTl: '시간 + 있어요 = "May oras?"',
      },
      {
        kind: 'choice',
        prompt: 'Listen. Which word?',
        speak: '없어요',
        options: ['있어요', '없어요', '아니요'],
        answer: '없어요',
        why: '없어요 is "eopseoyo".',
        whyTl: 'Narinig mo ang "eopseoyo": 없어요 = wala.',
      },
    ],
  },
  {
    id: '1.6',
    phase: 1,
    title: 'Sino-Korean numbers',
    ko: '일 이 삼',
    blurb: 'For money, dates, phone numbers and floors.',
    items: [
      { id: 'n.일', korean: '일', english: '1' },
      { id: 'n.이', korean: '이', english: '2' },
      { id: 'n.삼', korean: '삼', english: '3' },
      { id: 'n.사', korean: '사', english: '4' },
      { id: 'n.오', korean: '오', english: '5' },
      { id: 'n.십', korean: '십', english: '10' },
      { id: 'n.백', korean: '백', english: '100' },
      { id: 'n.천', korean: '천', english: '1,000' },
      { id: 'n.만', korean: '만', english: '10,000' },
      { id: 's.오천원', korean: '오천 원이에요.', english: 'It is 5,000 won.' },
    ],
    steps: [
      {
        kind: 'teach',
        title: 'Two number systems',
        body: [
          'Korean has two ways to count. Sino-Korean numbers (from Chinese) are used for money, dates, phone numbers, minutes and floors. Native Korean numbers are used for counting things and age. We learn Sino-Korean first.',
          '일 이 삼 사 오 육 칠 팔 구 십: 1 to 10.',
        ],
        tl: ['Dalawang sistema ng numero, parang Tagalog din: "isa, dalawa, tatlo" (native) at "uno, dos, tres" (hiram sa Spanish). Sa Korean, ang hiram sa Chinese ang gamit sa pera at petsa.'],
        tip: 'Ang Sino-Korean ay para sa pera, petsa, numero ng telepono, minuto. Hindi ito para sa pagbibilang ng bagay.',
        remember: 'Parang "uno dos tres" sa Pilipinas: ginagamit sa pera at oras. Ganoon din ang 일 이 삼 sa Korea.',
        glyphs: [
          { ch: '일', sub: '1' },
          { ch: '이', sub: '2' },
          { ch: '삼', sub: '3' },
          { ch: '사', sub: '4' },
          { ch: '오', sub: '5' },
          { ch: '육', sub: '6' },
          { ch: '칠', sub: '7' },
          { ch: '팔', sub: '8' },
          { ch: '구', sub: '9' },
          { ch: '십', sub: '10' },
        ],
      },
      {
        kind: 'teach',
        title: 'Building bigger numbers',
        body: [
          'The system is regular. 11 is 십일 (ten-one). 20 is 이십 (two-ten). 35 is 삼십오 (three-ten-five).',
          'Big units: 백 (100), 천 (1,000), 만 (10,000). Korean counts in units of 10,000, not 1,000.',
        ],
        tl: ['Simple ang pattern. 20 = "dalawang-sampu" = 이십. 35 = "tatlong-sampu-lima" = 삼십오. Walang kailangang magbago.'],
        tip: 'Ang 10,000 ay 만, kaya ang 50,000 won ay 오만 원 ("limang man"), hindi "limampung libo". Masanay ka sa man.',
        remember: '만 ay "man" = sampung libo. Isipin mong "isang man" ay "isang Man ng pera".',
        phrases: [
          { ko: '십오', en: '15', rom: 'sibo' },
          { ko: '이십', en: '20', rom: 'isip' },
          { ko: '오천 원', en: '5,000 won', rom: 'ocheon won' },
          { ko: '삼만 원', en: '30,000 won', rom: 'samman won' },
        ],
      },
      {
        kind: 'choice',
        prompt: 'What is 삼?',
        big: '삼',
        options: ['2', '3', '4'],
        answer: '3',
        why: '삼 is 3 (sam).',
        whyTl: '삼 = tatlo (sam).',
      },
      {
        kind: 'choice',
        prompt: 'How do you say 20?',
        options: ['이십', '십이', '이이'],
        answer: '이십',
        why: '2 × 10 = 이십. 십이 would be 12.',
        whyTl: '20 = 2 × 10 = 이십. Ang 십이 ay 12.',
      },
      {
        kind: 'choice',
        prompt: 'How much is 오천 원?',
        big: '오천 원',
        options: ['500 won', '5,000 won', '50,000 won'],
        answer: '5,000 won',
        why: '오 (5) × 천 (1,000) = 5,000.',
        whyTl: '오 (5) × 천 (1,000) = 5,000.',
      },
      {
        kind: 'choice',
        prompt: 'How do you say 50,000 won?',
        options: ['오만 원', '오천 원', '오백 원'],
        answer: '오만 원',
        why: '5 × 10,000 = 오만.',
        whyTl: '5 × 10,000 = 오만. Tandaan: man = 10,000.',
      },
    ],
  },
  {
    id: '1.7',
    phase: 1,
    title: 'Native Korean numbers',
    ko: '하나 둘 셋',
    blurb: 'For counting things and people.',
    items: [
      { id: 'n.하나', korean: '하나', english: '1 (native)' },
      { id: 'n.둘', korean: '둘', english: '2 (native)' },
      { id: 'n.셋', korean: '셋', english: '3 (native)' },
      { id: 'n.넷', korean: '넷', english: '4 (native)' },
      { id: 'n.다섯', korean: '다섯', english: '5 (native)' },
      { id: 'w.잔', korean: '잔', english: 'cup (counter)' },
      { id: 'w.명', korean: '명', english: 'person (counter)' },
    ],
    steps: [
      {
        kind: 'teach',
        title: 'One to ten, native style',
        body: [
          '하나 둘 셋 넷 다섯 여섯 일곱 여덟 아홉 열: 1 to 10.',
          'These are used for counting things, people and age. They go together with a counter word like 잔 (cup) or 명 (person).',
        ],
        tl: ['Ito ang "isa, dalawa, tatlo" ng Korean. Ginagamit sa pagbibilang ng bagay at tao, kasama ng counter word, katulad ng "isang tasa", "dalawang tao".'],
        tip: 'Hindi mo kailangang tandaan ang lahat ngayon. Una: 하나 둘 셋 넷 sapat na para sa pag-order ng kape.',
        remember: 'Ang 열 (yeol) = sampu. Isipin mong "yeol" ay "init", parang puno na ang kamay, sampung daliri.',
        glyphs: [
          { ch: '하나', sub: '1' },
          { ch: '둘', sub: '2' },
          { ch: '셋', sub: '3' },
          { ch: '넷', sub: '4' },
          { ch: '다섯', sub: '5' },
        ],
      },
      {
        kind: 'teach',
        title: 'Number + counter',
        body: [
          'Before a counter, 하나 둘 셋 넷 shorten to 한 두 세 네. So: 한 잔 (one cup), 두 잔 (two cups), 세 명 (three people).',
          'The counter comes after the number, and the object comes before both: 커피 두 잔.',
        ],
        tl: ['Bago ang counter, pinapaikli ang numero: 하나 → 한, 둘 → 두, 셋 → 세, 넷 → 네. "Kape, dalawang tasa" = 커피 두 잔.'],
        tip: 'Isipin mong ang Korean ay parang Tagalog sa pag-order: "Kape, dalawa." Una ang bagay, tapos ang dami.',
        remember: 'Parang sa Tagalog: "isang" (isa + ng), ganoon din sa 한 (하나 na pinaikli). Pinapaikli rin.',
        phrases: [
          { ko: '한 잔', en: 'one cup', rom: 'han jan' },
          { ko: '두 잔', en: 'two cups', rom: 'du jan' },
          { ko: '세 명', en: 'three people', rom: 'se myeong' },
          { ko: '네 명', en: 'four people', rom: 'ne myeong' },
        ],
      },
      {
        kind: 'choice',
        prompt: 'What is 둘?',
        big: '둘',
        options: ['1', '2', '3'],
        answer: '2',
        why: '둘 is 2.',
        whyTl: '둘 = dalawa.',
      },
      {
        kind: 'choice',
        prompt: 'How do you say "two cups"?',
        options: ['두 잔', '이 잔', '둘 잔'],
        answer: '두 잔',
        why: 'Native numbers before counters: 둘 becomes 두.',
        whyTl: 'Native number + counter, at ang 둘 ay nagiging 두.',
      },
      {
        kind: 'choice',
        prompt: 'Which number system do you use for 5,000 won?',
        options: ['Sino-Korean (오천)', 'Native (다섯천)'],
        answer: 'Sino-Korean (오천)',
        why: 'Money always uses Sino-Korean numbers.',
        whyTl: 'Pera = Sino-Korean, laging.',
      },
    ],
  },
  {
    id: '1.8',
    phase: 1,
    title: 'Polite requests: -주세요',
    ko: '주세요',
    blurb: 'How to order, ask and shop politely.',
    items: [
      { id: 's.물주세요', korean: '물 주세요.', english: 'Water, please.' },
      { id: 's.이거주세요', korean: '이거 주세요.', english: 'This one, please.' },
      { id: 's.커피한잔주세요', korean: '커피 한 잔 주세요.', english: 'One coffee, please.' },
      { id: 'w.여기요', korean: '여기요', english: 'excuse me (calling staff)' },
    ],
    steps: [
      {
        kind: 'teach',
        title: 'Noun + 주세요',
        body: [
          '주세요 means "please give me". Put what you want in front of it: 물 주세요, "water, please".',
          'This one pattern lets you order food, buy things and ask for help.',
        ],
        tl: ['Ito ang "pahingi po" o "pabili po". 물 주세요 = "Pahingi ng tubig." Ito ang pinakamahalagang pangungusap sa pamimili at pagkain.'],
        tip: 'Kapag tumuturo ka sa menu, sabihin lang 이거 주세요. Walang kailangang matutunan na pangalan.',
        remember: '주 ay parang "ju", at "juice" ay madalas ang unang inoorder: 주스 주세요.',
        phrases: [
          { ko: '물 주세요.', en: 'Water, please.', rom: 'mul juseyo' },
          { ko: '이거 주세요.', en: 'This one, please.', rom: 'igeo juseyo' },
          { ko: '커피 한 잔 주세요.', en: 'One coffee, please.', rom: 'keopi han jan juseyo' },
        ],
      },
      {
        kind: 'teach',
        title: 'Getting attention',
        body: [
          'In Korean restaurants it is normal to call the staff with 여기요 ("over here"). It is not rude.',
          'Combine everything: 여기요, 물 두 잔 주세요. "Excuse me, two glasses of water, please."',
        ],
        tl: ['Sa Korea, normal na tumawag ng staff ng "여기요!" Hindi bastos. Parang "Ate, pabili!" sa tindahan natin.'],
        tip: 'Sa maraming restaurant, may call button sa mesa. Pindutin lang, at darating ang staff.',
        remember: '여기 = dito. 여기요 = "Dito po!" Simple.',
        phrases: [
          { ko: '여기요!', en: 'Excuse me!', rom: 'yeogiyo' },
          { ko: '여기요, 물 두 잔 주세요.', en: 'Excuse me, two glasses of water, please.' },
          { ko: '감사합니다.', en: 'Thank you.', rom: 'gamsahamnida' },
        ],
      },
      {
        kind: 'choice',
        prompt: 'How do you ask for water politely?',
        options: ['물 주세요.', '물이에요.', '물 있어요.'],
        answer: '물 주세요.',
        why: '주세요 means "please give me".',
        whyTl: '주세요 = pahingi po.',
      },
      {
        kind: 'choice',
        prompt: 'What does 커피 한 잔 주세요 mean?',
        big: '커피 한 잔 주세요',
        options: ['One coffee, please.', 'Two coffees, please.', 'I am a coffee.'],
        answer: 'One coffee, please.',
        why: '한 잔 = one cup. 커피 한 잔 = one cup of coffee.',
        whyTl: '한 잔 = isang tasa. "Isang kape po."',
      },
      {
        kind: 'choice',
        prompt: 'You want to call the waiter. What do you say?',
        options: ['여기요', '안녕히 계세요', '아니요'],
        answer: '여기요',
        why: '여기요 is the normal way to get staff attention.',
        whyTl: '여기요 = "Dito po!"',
      },
    ],
  },

  {
    id: '2.1',
    phase: 2,
    title: 'Subject marker: 이 / 가',
    ko: '이 / 가',
    blurb: 'Who or what does the action. How it differs from 은 / 는.',
    items: [
      { id: 's.날씨가좋아요', korean: '날씨가 좋아요.', english: 'The weather is nice.' },
      { id: 'w.날씨', korean: '날씨', english: 'weather' },
      { id: 'w.좋아요', korean: '좋아요', english: 'is good / I like it' },
    ],
    steps: [
      {
        kind: 'teach',
        title: 'The subject marker',
        body: [
          '이 and 가 mark the subject: the thing the sentence is about, often new information. After a consonant use 이, after a vowel use 가.',
          '날씨가 좋아요: "The weather is good." 날씨 ends in a vowel, so 가.',
        ],
        tl: ['Ang 이/가 ay nagsasabi kung sino o ano ang gumagawa o may katangian. Parang "ang" sa Tagalog. Kapag may batchim, 이. Kapag wala, 가.'],
        tip: 'Parehong rule sa 은/는: consonant → 이, vowel → 가.',
        remember: 'Ang 가 ay simple at walang batchim, kaya sumasama sa salitang walang batchim.',
        phrases: [
          { ko: '날씨가 좋아요.', en: 'The weather is nice.', rom: 'nalssiga joayo' },
          { ko: '사람이 많아요.', en: 'There are many people.', rom: 'sarami manayo' },
        ],
      },
      {
        kind: 'teach',
        title: '은/는 vs 이/가',
        body: [
          '은/는 sets the topic: "As for X...". 이/가 introduces or points at the subject: "X is the one that...".',
          'A simple rule of thumb: use 이/가 for new things and for question words like 뭐가 (what) or 누가 (who). Use 은/는 for things already known.',
        ],
        tl: ['Isipin mo: 은/는 = "Tungkol sa X..." (alam na ng dalawa). 이/가 = "Si X ang..." (bagong impormasyon).'],
        tip: 'Huwag mag-alala kung hindi pa malinaw. Kahit mga Korean ay minsan nagtatalo dito. Maraming exposure lang ang solusyon.',
        remember: 'Topic → 은/는 (alam na). Subject → 이/가 (bago, o tinuturo).',
        phrases: [
          { ko: '저는 학생이에요.', en: 'As for me, I am a student.' },
          { ko: '누가 학생이에요?', en: 'Who is the student?' },
        ],
      },
      {
        kind: 'choice',
        prompt: 'Which marker goes after 날씨 (ends in a vowel)?',
        options: ['이', '가'],
        answer: '가',
        why: '날씨 ends in 씨 (a vowel sound), so 가.',
        whyTl: 'Walang batchim ang 날씨, kaya 가.',
      },
      {
        kind: 'choice',
        prompt: 'Which marker goes after 사람 (ends in ㅁ)?',
        options: ['이', '가'],
        answer: '이',
        why: '사람 ends in a consonant, so 이.',
        whyTl: 'May batchim ang 사람, kaya 이.',
      },
      {
        kind: 'choice',
        prompt: 'What does 날씨가 좋아요 mean?',
        big: '날씨가 좋아요',
        options: ['The weather is nice.', 'I like the weather forecast.', 'I am a student.'],
        answer: 'The weather is nice.',
        why: '날씨 = weather, 좋아요 = is good.',
        whyTl: '날씨 = panahon, 좋아요 = maganda. "Maganda ang panahon."',
      },
    ],
  },
  {
    id: '2.2',
    phase: 2,
    title: 'Object marker: 을 / 를',
    ko: '을 / 를',
    blurb: 'What the action is done to.',
    items: [
      { id: 's.밥을먹어요', korean: '밥을 먹어요.', english: 'I eat a meal.' },
      { id: 's.커피를마셔요', korean: '커피를 마셔요.', english: 'I drink coffee.' },
      { id: 'w.먹어요', korean: '먹어요', english: 'eat' },
      { id: 'w.마셔요', korean: '마셔요', english: 'drink' },
    ],
    steps: [
      {
        kind: 'teach',
        title: 'Marking the object',
        body: [
          '을 and 를 mark the object: the thing that receives the action. After a consonant use 을, after a vowel use 를.',
          'Korean word order is subject, object, verb. The verb is always last: 저는 밥을 먹어요, literally "I rice eat".',
        ],
        tl: ['Ang 을/를 ay nagsasabi kung ano ang pinagkakaabalahan ng verb. Hindi katulad sa English, ang verb ay laging nasa dulo: "Ako kanin kumakain."'],
        tip: 'Sa pang-araw-araw na usapan, madalas inaalis ang 을/를. 밥 먹어요 ay okay. Pero isulat mo muna nang kumpleto habang nag-aaral.',
        remember: 'Verb sa dulo, parang Tagalog pa rin: "Kumain ako ng kanin." Pero Korean ay "Ako kanin kumain" (SOV).',
        phrases: [
          { ko: '밥을 먹어요.', en: 'I eat a meal.', rom: 'babeul meogeoyo' },
          { ko: '커피를 마셔요.', en: 'I drink coffee.', rom: 'keopireul masyeoyo' },
        ],
      },
      {
        kind: 'teach',
        title: 'Two verbs to start',
        body: ['먹어요 means eat. 마셔요 means drink. We will learn how they are built in the next lesson.'],
        tl: ['Gamitin muna sila bilang dalawang salita lang: 먹어요 = kain, 마셔요 = inom. Susunod nating aaralin kung paano sila nabuo.'],
        tip: 'Ang 마시다 ay para sa lahat ng inumin: tubig, kape, alak. Hindi mo kailangan ng iba.',
        remember: '먹 = "meok" = mukbang. Sikat na Korean word: 먹방!',
        phrases: [
          { ko: '김치를 먹어요.', en: 'I eat kimchi.' },
          { ko: '물을 마셔요.', en: 'I drink water.' },
        ],
      },
      {
        kind: 'choice',
        prompt: 'Which marker goes after 밥 (ends in ㅂ)?',
        options: ['을', '를'],
        answer: '을',
        why: '밥 has batchim, so 을.',
        whyTl: 'May batchim ang 밥, kaya 을.',
      },
      {
        kind: 'choice',
        prompt: 'Which marker goes after 커피 (ends in a vowel)?',
        options: ['을', '를'],
        answer: '를',
        why: '커피 ends in a vowel, so 를.',
        whyTl: 'Walang batchim ang 커피, kaya 를.',
      },
      {
        kind: 'choice',
        prompt: 'What does 물을 마셔요 mean?',
        big: '물을 마셔요',
        options: ['I drink water.', 'I eat water.', 'There is water.'],
        answer: 'I drink water.',
        why: '물 = water, 을 = object marker, 마셔요 = drink.',
        whyTl: '물 + 을 + 마셔요 = "Umiinom ako ng tubig."',
      },
    ],
  },
  {
    id: '2.3',
    phase: 2,
    title: 'Present polite: -아요 / -어요',
    ko: '해요체',
    blurb: 'How every verb ends in everyday polite speech.',
    items: [
      { id: 'v.가요', korean: '가요', english: 'go' },
      { id: 'v.와요', korean: '와요', english: 'come' },
      { id: 'v.먹어요', korean: '먹어요', english: 'eat' },
      { id: 'v.마셔요', korean: '마셔요', english: 'drink' },
      { id: 'v.공부해요', korean: '공부해요', english: 'study' },
    ],
    steps: [
      {
        kind: 'teach',
        title: 'Dictionary form ends in 다',
        body: [
          'Dictionary forms end in 다: 가다 (to go), 먹다 (to eat). Remove 다 to get the stem: 가, 먹.',
          'Then add 아요 or 어요. If the last vowel of the stem is ㅏ or ㅗ, add 아요. Otherwise, add 어요.',
        ],
        tl: ['Ang verb sa diksyunaryo ay laging nagtatapos sa 다. Alisin ang 다 para makuha ang stem, tapos dagdagan ng 아요 o 어요. Kapag ㅏ o ㅗ ang huling vowel, 아요. Kapag iba, 어요.'],
        tip: 'Ang ㅏ at ㅗ ay tinatawag na "bright vowels". Lahat ng iba ay "dark". Bright + 아요, dark + 어요.',
        remember: '아 sa 아요 ay bright, kaya sumasama sa ㅏ ㅗ. 어 sa 어요 ay dark, sumasama sa iba. Parang magkakaparehong kulay.',
        phrases: [
          { ko: '먹다 → 먹어요', en: 'eat', rom: 'meokda → meogeoyo' },
          { ko: '좋다 → 좋아요', en: 'be good', rom: 'jota → joayo' },
        ],
      },
      {
        kind: 'teach',
        title: 'Contractions',
        body: [
          'When the stem ends in a vowel, the vowels merge. 가 + 아요 = 가요 (not 가아요). 오 + 아요 = 와요. 마시 + 어요 = 마셔요.',
          '하다 verbs are special: 공부하다 becomes 공부해요. Anything ending in 하다 becomes 해요.',
        ],
        tl: ['Kapag ang stem ay nagtatapos sa vowel, nagsasama ang vowels: 가 + 아요 = 가요. 마시 + 어요 = 마셔요. Parang sa Tagalog na "hindi ko" ay nagiging "di ko".', 'Lahat ng verb na nagtatapos sa 하다 ay 해요: 공부해요, 일해요, 운동해요.'],
        tip: 'Ang 하다 ay super common. Sa sandaling matuto ka ng "noun + 하다", marami ka nang verbs: 공부하다 (study), 운동하다 (exercise).',
        remember: 'Ang 해요 ay isa sa pinakamahalaga. Kapag nakita mo ang 하, sabihin mo agad 해요.',
        phrases: [
          { ko: '가요', en: 'go', rom: 'gayo' },
          { ko: '와요', en: 'come', rom: 'wayo' },
          { ko: '마셔요', en: 'drink', rom: 'masyeoyo' },
          { ko: '공부해요', en: 'study', rom: 'gongbuhaeyo' },
        ],
      },
      {
        kind: 'choice',
        prompt: 'Make the polite present of 먹다 (stem 먹).',
        options: ['먹아요', '먹어요', '먹요'],
        answer: '먹어요',
        why: 'The vowel in 먹 is ㅓ (not ㅏ or ㅗ), so 어요.',
        whyTl: 'ㅓ ang vowel ng 먹, hindi bright, kaya 어요.',
      },
      {
        kind: 'choice',
        prompt: 'Make the polite present of 가다 (stem 가).',
        options: ['가아요', '가요', '가어요'],
        answer: '가요',
        why: '가 + 아요 merges into 가요.',
        whyTl: '가 + 아요 → 가요. Nagsasama ang dalawang 아.',
      },
      {
        kind: 'choice',
        prompt: 'What is the polite present of 공부하다?',
        options: ['공부해요', '공부하요', '공부하어요'],
        answer: '공부해요',
        why: 'All 하다 verbs become 해요.',
        whyTl: 'Lahat ng 하다 ay nagiging 해요.',
      },
      {
        kind: 'choice',
        prompt: 'Which sentence is correct?',
        options: ['저는 커피를 마셔요.', '저는 커피를 마시어요.', '저는 마셔요 커피를.'],
        answer: '저는 커피를 마셔요.',
        why: 'Verb last, and 마시 + 어요 contracts to 마셔요.',
        whyTl: 'Verb sa dulo, at 마시 + 어요 = 마셔요.',
      },
    ],
  },
  {
    id: '2.4',
    phase: 2,
    title: 'Negation: 안',
    ko: '안',
    blurb: 'The easiest way to say "do not".',
    items: [
      { id: 's.안먹어요', korean: '안 먹어요.', english: 'I do not eat.' },
      { id: 's.안가요', korean: '안 가요.', english: 'I do not go.' },
      { id: 's.공부안해요', korean: '공부 안 해요.', english: 'I do not study.' },
    ],
    steps: [
      {
        kind: 'teach',
        title: 'Put 안 before the verb',
        body: [
          'To make a verb negative, add 안 right before it: 먹어요 (eat) → 안 먹어요 (do not eat). 가요 → 안 가요.',
          'For 하다 verbs, 안 goes between the noun and 해요: 공부해요 → 공부 안 해요.',
        ],
        tl: ['Ito ang "hindi" ng Korean. Ilagay lang sa harap ng verb: 먹어요 → 안 먹어요 ("hindi kumakain"). Kapag 하다 verb, nasa gitna: 공부 안 해요.'],
        tip: 'Ang 안 ay maiksi at mabilis. Basahin mo na parang "an" na nakadikit sa verb: "anmeogeoyo".',
        remember: '안 ay "an", parang "hin-" ng "hindi". Hindi + verb = 안 + verb.',
        phrases: [
          { ko: '안 먹어요.', en: 'I do not eat.', rom: 'an meogeoyo' },
          { ko: '안 가요.', en: 'I do not go.', rom: 'an gayo' },
          { ko: '공부 안 해요.', en: 'I do not study.', rom: 'gongbu an haeyo' },
        ],
      },
      {
        kind: 'choice',
        prompt: 'How do you say "I do not drink coffee"?',
        options: ['커피를 안 마셔요.', '커피를 마셔요 안.', '안 커피를 마셔요.'],
        answer: '커피를 안 마셔요.',
        why: '안 goes right before the verb.',
        whyTl: 'Ang 안 ay laging nasa harap ng verb.',
      },
      {
        kind: 'choice',
        prompt: 'How do you say "I do not study"?',
        options: ['공부 안 해요.', '안 공부해요.', '공부해요 안.'],
        answer: '공부 안 해요.',
        why: 'For 하다 verbs, 안 goes between the noun and 해요.',
        whyTl: 'Sa 하다 verbs, nasa gitna ang 안: 공부 + 안 + 해요.',
      },
      {
        kind: 'choice',
        prompt: 'What does 안 가요 mean?',
        big: '안 가요',
        options: ['I do not go.', 'I go.', 'I do not come.'],
        answer: 'I do not go.',
        why: '안 = not, 가요 = go.',
        whyTl: '안 + 가요 = "Hindi ako pupunta."',
      },
    ],
  },
];

export const UPCOMING2: { id: string; title: string; ko: string }[] = [
  { id: '2.5', title: 'Location: 에 vs 에서', ko: '에 / 에서' },
  { id: '2.6', title: 'Past tense', ko: '-았어요 / -었어요' },
  { id: '2.7', title: 'Wanting: -고 싶어요', ko: '-고 싶어요' },
  { id: '2.8', title: 'Future and plans', ko: '-(으)ㄹ 거예요' },
  { id: '2.9', title: 'Linking sentences', ko: '-고, 그리고, 그런데' },
  { id: '2.10', title: 'Can and cannot', ko: '-(으)ㄹ 수 있어요' },
];
