import type { Lesson, Step } from './lessons';

type Ph = { ko: string; en: string; rom?: string };

/** Teaching card: title, English body, Taglish, pro tip, memory hook, phrase cards. */
const tc = (title: string, body: string[], tl: string, tip: string, remember: string, phrases: Ph[]): Step => ({
  kind: 'teach',
  title,
  body,
  tl: [tl],
  tip,
  remember,
  phrases,
});

/** Multiple choice. The right answer is slotted in at a varying position. */
const ch = (
  prompt: string,
  answer: string,
  wrong: string[],
  why: string,
  whyTl: string,
  extra: { big?: string; speak?: string } = {},
): Step => {
  const options = [...wrong];
  options.splice(prompt.length % (wrong.length + 1), 0, answer);
  return { kind: 'choice', prompt, options, answer, why, whyTl, ...extra };
};

const it = (id: string, korean: string, english: string) => ({ id: `e.${id}`, korean, english });

export const EVERYDAY: Lesson[] = [
  {
    id: '3.1',
    phase: 3,
    title: 'Introducing yourself',
    ko: '자기소개',
    blurb: 'Meet someone and tell them who you are.',
    items: [
      it('처음뵙겠습니다', '처음 뵙겠습니다.', 'Nice to meet you (formal, first time).'),
      it('만나서반갑습니다', '만나서 반갑습니다.', 'Glad to meet you.'),
      it('이름이뭐예요', '이름이 뭐예요?', 'What is your name?'),
      it('제이름은', '제 이름은 마리아예요.', 'My name is Maria.'),
      it('어디에서왔어요', '어디에서 왔어요?', 'Where are you from?'),
      it('필리핀에서왔어요', '필리핀에서 왔어요.', 'I am from the Philippines.'),
    ],
    steps: [
      tc(
        'The first minute',
        ['When you meet someone, say 처음 뵙겠습니다 (formal "nice to meet you") or 만나서 반갑습니다 (glad to meet you). Both are polite and safe.', 'Then give your name: 제 이름은 ___예요 / 이에요. 제 is the humble form of "my".'],
        'Ito ang "Ikinagagalak kitang makilala." Pagkatapos, sabihin ang pangalan mo: 제 이름은 마리아예요. Gamitin ang 예요 kung walang batchim ang pangalan, 이에요 kung meron (lesson 1.2).',
        'Yumuko nang bahagya habang sinasabi ito. Ang tono ay magalang pero hindi malamig.',
        '반갑습니다 = "bangap" = "bagay, masaya". Isipin mo: "Bang! Masaya akong makilala ka."',
        [
          { ko: '처음 뵙겠습니다.', en: 'Nice to meet you (first time, formal).', rom: 'cheoeum boepgetseumnida' },
          { ko: '만나서 반갑습니다.', en: 'Glad to meet you.', rom: 'mannaseo bangapseumnida' },
          { ko: '제 이름은 마리아예요.', en: 'My name is Maria.', rom: 'je ireumeun mariayeyo' },
        ],
      ),
      tc(
        'Where are you from?',
        ['어디 means "where". 에서 (lesson 2.5) plus 왔어요 ("came") asks where you came from: 어디에서 왔어요?', 'Answer with the country and 에서 왔어요: 필리핀에서 왔어요, 미국에서 왔어요.'],
        'Ang tanong ay "Saan ka galing?" Ang sagot: [bansa] + 에서 왔어요. 필리핀에서 왔어요 = "Galing ako sa Pilipinas."',
        'Puwede ring 저는 필리핀 사람이에요 (lesson 1.3). Dalawang paraan, parehong tama.',
        '왔어요 ay nanggaling sa 오다 (come). Tandaan: 에서 = "from" sa kontekstong ito.',
        [
          { ko: '어디에서 왔어요?', en: 'Where are you from?', rom: 'eodieseo wasseoyo' },
          { ko: '필리핀에서 왔어요.', en: 'I am from the Philippines.', rom: 'pillipineseo wasseoyo' },
          { ko: '미국에서 왔어요.', en: 'I am from the USA.', rom: 'migugeseo wasseoyo' },
        ],
      ),
      ch('Which phrase is a polite "nice to meet you"?', '만나서 반갑습니다.', ['안녕히 계세요.', '죄송합니다.'], '만나서 반갑습니다 means "glad to meet you".', 'Ang 만나서 반갑습니다 ay "Masaya akong makilala ka."'),
      ch('How do you ask "What is your name?"', '이름이 뭐예요?', ['어디에서 왔어요?', '이거 뭐예요?'], '이름 = name, 뭐예요 = what is it.', '이름 = pangalan, 뭐예요 = ano.'),
      ch('How do you say "I am from the Philippines"?', '필리핀에서 왔어요.', ['필리핀에 갔어요.', '필리핀을 먹어요.'], '에서 왔어요 = came from.', '에서 왔어요 = galing sa.'),
    ],
  },
  {
    id: '3.2',
    phase: 3,
    title: 'Fillers and reactions',
    ko: '맞장구',
    blurb: 'Keep a conversation alive and survive when you do not understand.',
    items: [
      it('그래요', '그래요?', 'Oh, really? / Is that so?'),
      it('정말요', '정말요?', 'Really?'),
      it('맞아요', '맞아요.', 'That is right.'),
      it('글쎄요', '글쎄요.', 'Well... / I am not sure.'),
      it('괜찮아요', '괜찮아요.', 'It is okay.'),
      it('알겠어요', '알겠어요.', 'I got it.'),
      it('모르겠어요', '모르겠어요.', 'I do not know / understand.'),
      it('잠깐만요', '잠깐만요.', 'Just a moment.'),
      it('천천히말해주세요', '천천히 말해 주세요.', 'Please speak slowly.'),
      it('다시한번', '다시 한번 말해 주세요.', 'Please say it once more.'),
    ],
    steps: [
      tc(
        'Reaction words',
        ['Koreans react a lot while listening, and so should you. A small reaction shows you are following.', '그래요? and 정말요? both mean "really?". 맞아요 means "right, exactly". 글쎄요 is "well... I am not sure".'],
        'Parang "Talaga?", "Ganun ba?", "Tama!", at "Ewan ko, siguro." Gamitin ang mga ito para hindi ka maging tahimik sa usapan.',
        'Itaas ang tono sa dulo ng 그래요? at 정말요? para tunog tanong. Ibaba para tunog "ah, ganun pala".',
        '정말요 = "jeongmal" = "talaga". Isipin mong "jong-mal": talaga, hindi biro.',
        [
          { ko: '그래요?', en: 'Oh, really?', rom: 'geuraeyo' },
          { ko: '정말요?', en: 'Really?', rom: 'jeongmallyo' },
          { ko: '맞아요.', en: 'That is right.', rom: 'majayo' },
          { ko: '글쎄요.', en: 'Well... I am not sure.', rom: 'geulsseyo' },
        ],
      ),
      tc(
        'Everyday okay-ness',
        ['괜찮아요 is the most useful word in Korean. It means "it is okay", "I am fine", "no problem", and "no thank you" depending on the tone.', '알겠어요 means "I understand / got it". 모르겠어요 means "I do not know / I do not understand".'],
        'Ang 괜찮아요 ay "Okay lang", "Ayos lang", "Wag na po" depende sa tono. Ang 알겠어요 ay "Gets ko." Ang 모르겠어요 ay "Hindi ko alam / maintindihan."',
        'Kung may nag-aalok ng bagay at ayaw mo, sabihin lang 괜찮아요 at iling ng kamay. Magalang ito.',
        '괜찮아요 ay mahaba, pero isipin: "gwen-cha-na-yo" = "gwen chana (chance) yo": "okay lang, may chance pa."',
        [
          { ko: '괜찮아요.', en: 'It is okay / no thank you.', rom: 'gwaenchanayo' },
          { ko: '알겠어요.', en: 'I got it.', rom: 'algesseoyo' },
          { ko: '모르겠어요.', en: 'I do not know / understand.', rom: 'moreugesseoyo' },
        ],
      ),
      tc(
        'When you are lost in the conversation',
        ['These are your lifelines. 잠깐만요 asks for a moment. 천천히 말해 주세요 asks the speaker to slow down. 다시 한번 말해 주세요 asks them to say it again.', '말해 주세요 is the pattern "please do X for me". You will learn it properly later, but you can already use it.'],
        'Ito ang "Sandali lang", "Pakibagalan po", at "Pakiulit po." Ito ang pinakamahalagang parirala kapag nawawala ka sa usapan.',
        'Walang nakakahiya sa pagsabi ng 천천히 말해 주세요. Maiintindihan ka ng mga Koreano at mas magiging mabagal sila.',
        '천천히 = "cheon-cheon-hi" = "dahan-dahan". Maraming "cheon" ay marami ring "dahan".',
        [
          { ko: '잠깐만요.', en: 'Just a moment.', rom: 'jamkkanmanyo' },
          { ko: '천천히 말해 주세요.', en: 'Please speak slowly.', rom: 'cheoncheonhi malhae juseyo' },
          { ko: '다시 한번 말해 주세요.', en: 'Please say it once more.', rom: 'dasi hanbeon malhae juseyo' },
        ],
      ),
      ch('Someone offers you more food but you are full. What do you say?', '괜찮아요.', ['정말요?', '맞아요.'], '괜찮아요 politely means "I am fine / no thank you".', '괜찮아요 = "Okay na ako, salamat."'),
      ch('You did not catch what they said. What do you say?', '다시 한번 말해 주세요.', ['알겠어요.', '맞아요.'], '다시 한번 = once more, 말해 주세요 = please say.', '다시 한번 = isa pa, 말해 주세요 = pakisabi.'),
      ch('What does 모르겠어요 mean?', 'I do not know / understand.', ['I got it.', 'It is okay.'], '모르겠어요 is the opposite of 알겠어요.', '모르겠어요 = hindi ko alam. 알겠어요 = gets ko.', { big: '모르겠어요' }),
    ],
  },
  {
    id: '3.3',
    phase: 3,
    title: 'At a restaurant',
    ko: '식당에서',
    blurb: 'From being seated to paying.',
    items: [
      it('몇분이세요', '몇 분이세요?', 'How many people?'),
      it('두명이에요', '두 명이에요.', 'Two people.'),
      it('메뉴판주세요', '메뉴판 주세요.', 'Menu, please.'),
      it('이거하나주세요', '이거 하나 주세요.', 'One of this, please.'),
      it('물좀주세요', '물 좀 주세요.', 'Some water, please.'),
      it('많이매워요', '많이 매워요?', 'Is it very spicy?'),
      it('맛있어요', '맛있어요.', 'It is delicious.'),
      it('잘먹겠습니다', '잘 먹겠습니다.', 'I will eat well (said before eating).'),
      it('잘먹었습니다', '잘 먹었습니다.', 'I ate well (said after eating).'),
      it('계산해주세요', '계산해 주세요.', 'The bill, please.'),
    ],
    steps: [
      tc(
        'Getting seated and ordering',
        ['The host will ask 몇 분이세요? ("how many people?"). Answer with a native number and 명: 두 명이에요 (lesson 1.7).', 'Ask for the menu with 메뉴판 주세요, and order by pointing: 이거 하나 주세요 ("one of this, please").'],
        'Ang staff ay magtatanong ng 몇 분이세요? Sagot: 한 명 / 두 명 / 세 명이에요. Pagkatapos: 메뉴판 주세요 (menu po), 이거 하나 주세요 (isa nito).',
        'Ang 좀 ay "kaunti" at ginagawang mas magalang ang request: 물 좀 주세요 = "Pakiabot po ng tubig."',
        '몇 = "ilan". 몇 분 = "ilan po kayo?" 분 ay magalang na "tao".',
        [
          { ko: '몇 분이세요?', en: 'How many people?', rom: 'myeot buniseyo' },
          { ko: '두 명이에요.', en: 'Two people.', rom: 'du myeongieyo' },
          { ko: '메뉴판 주세요.', en: 'Menu, please.', rom: 'menyupan juseyo' },
          { ko: '이거 하나 주세요.', en: 'One of this, please.', rom: 'igeo hana juseyo' },
        ],
      ),
      tc(
        'Talking about the food',
        ['맛있어요 means "it is delicious". Koreans say it a lot. Spicy food is 매워요. Ask 많이 매워요? ("is it very spicy?") before ordering.', 'Water is free in most restaurants. You usually help yourself, or ask 물 좀 주세요.'],
        'Ang 맛있어요 ay "masarap!". Kung takot ka sa anghang, tanungin: 많이 매워요? Tandaan, maraming Korean dish ay maanghang.',
        'Kung ayaw mo ng maanghang, sabihin 안 매워요? ("Hindi ba maanghang?") gamit ang 안 mula lesson 2.4.',
        '맛있어요 = "masisseoyo" = "masi-ssoyo". Parang "masarap" at "masi" ay halos magkatunog.',
        [
          { ko: '맛있어요.', en: 'It is delicious.', rom: 'masisseoyo' },
          { ko: '많이 매워요?', en: 'Is it very spicy?', rom: 'mani maewoyo' },
          { ko: '물 좀 주세요.', en: 'Some water, please.', rom: 'mul jom juseyo' },
        ],
      ),
      tc(
        'Before, after and the bill',
        ['Before eating say 잘 먹겠습니다 ("I will eat well"). After eating say 잘 먹었습니다 ("I ate well"). It thanks the host or cook.', 'To pay, say 계산해 주세요 ("the bill, please"). In many restaurants you pay at the counter by the door.'],
        'Parang "Kain na tayo!" at "Salamat sa pagkain!" Sabihin bago at pagkatapos kumain. Ito ang magalang na paraan.',
        'Madalas, ang bayad ay sa counter malapit sa pinto, hindi sa mesa. Dalhin ang resibo mula sa mesa.',
        '먹겠습니다 (future: "will eat") bago kumain. 먹었습니다 (past: "ate") pagkatapos. Future before, past after.',
        [
          { ko: '잘 먹겠습니다.', en: 'I will eat well (before).', rom: 'jal meokgetseumnida' },
          { ko: '잘 먹었습니다.', en: 'I ate well (after).', rom: 'jal meogeotseumnida' },
          { ko: '계산해 주세요.', en: 'The bill, please.', rom: 'gyesanhae juseyo' },
        ],
      ),
      ch('The host asks 몇 분이세요? You are with one friend. What do you say?', '두 명이에요.', ['한 명이에요.', '세 명이에요.'], 'You plus a friend is 2: 두 명.', 'Ikaw + isang kaibigan = dalawa: 두 명.'),
      ch('You are about to eat. What do you say?', '잘 먹겠습니다.', ['잘 먹었습니다.', '계산해 주세요.'], '먹겠습니다 is the "before eating" phrase.', '먹겠습니다 = bago kumain.'),
      ch('You finished and want to pay. What do you say?', '계산해 주세요.', ['메뉴판 주세요.', '맛있어요.'], '계산 = payment, 해 주세요 = please do.', '계산 = bayad, 해 주세요 = pakigawa.'),
    ],
  },
  {
    id: '3.4',
    phase: 3,
    title: 'At a cafe',
    ko: '카페에서',
    blurb: 'Order your drink exactly how you like it.',
    items: [
      it('아메리카노한잔', '아이스 아메리카노 한 잔 주세요.', 'One iced Americano, please.'),
      it('여기에서먹을거예요', '여기에서 먹을 거예요.', 'I will eat here.'),
      it('포장해주세요', '포장해 주세요.', 'To go, please.'),
      it('카드돼요', '카드 돼요?', 'Can I pay by card?'),
      it('영수증주세요', '영수증 주세요.', 'A receipt, please.'),
      it('따뜻하게', '따뜻하게 주세요.', 'Hot, please.'),
    ],
    steps: [
      tc(
        'The order',
        ['The pattern is drink + number + 잔 + 주세요. 아이스 아메리카노 한 잔 주세요: "one iced Americano, please".', 'Many drinks are borrowed from English, so you can already read them: 라떼, 커피, 주스, 아이스, 핫.'],
        'Parehong-pareho sa 1.8: [inumin] + [bilang] + 잔 + 주세요. Mga pangalan ay hiram sa English, kaya basahin lang: 카페라떼, 아이스 커피.',
        'Ang "아이스" ay iced at ang "따뜻하게" ay hot. Sa Korea, ang default na kape ay madalas iced kahit taglamig.',
        '아이스 = ice, 라떼 = latte. Kung nababasa mo ang Hangul, nababasa mo ang menu.',
        [
          { ko: '아이스 아메리카노 한 잔 주세요.', en: 'One iced Americano, please.' },
          { ko: '따뜻하게 주세요.', en: 'Hot, please.', rom: 'ttatteuthage juseyo' },
          { ko: '라떼 두 잔 주세요.', en: 'Two lattes, please.' },
        ],
      ),
      tc(
        'Here, to go, and paying',
        ['The staff will ask whether you eat here or take away. Say 여기에서 먹을 거예요 (lesson 2.8: "I will eat here") or 포장해 주세요 ("package it, please").', 'To pay: 카드 돼요? ("is a card okay?") and 영수증 주세요 ("a receipt, please").'],
        'Ang tanong ng barista ay kung dito kakain o take-out. Sagot: 여기에서 먹을 거예요 (dito) o 포장해 주세요 (take out).',
        'Sa Korea, madalas ang cafe ay may pickup counter. Hintayin ang pangalan o numero mo.',
        '포장 = "pojang" = "pack". Pack it up = take-out.',
        [
          { ko: '여기에서 먹을 거예요.', en: 'I will eat here.', rom: 'yeogieseo meogeul geoyeyo' },
          { ko: '포장해 주세요.', en: 'To go, please.', rom: 'pojanghae juseyo' },
          { ko: '카드 돼요?', en: 'Can I pay by card?', rom: 'kadeu dwaeyo' },
          { ko: '영수증 주세요.', en: 'A receipt, please.', rom: 'yeongsujeung juseyo' },
        ],
      ),
      ch('You want your coffee to take away. What do you say?', '포장해 주세요.', ['여기에서 먹을 거예요.', '카드 돼요?'], '포장 means packaging, so 포장해 주세요 is "to go".', '포장해 주세요 = take-out, please.'),
      ch('How do you ask "Can I pay by card?"', '카드 돼요?', ['영수증 주세요.', '따뜻하게 주세요.'], '카드 = card, 돼요? = is it okay?', '카드 돼요? = Puwede ba ang card?'),
      ch('How do you order two lattes?', '라떼 두 잔 주세요.', ['라떼 이 잔 주세요.', '라떼 두 명 주세요.'], 'Native number 두 + counter 잔 (lesson 1.7).', 'Native number 두 + counter 잔.'),
    ],
  },
  {
    id: '3.5',
    phase: 3,
    title: 'Shopping',
    ko: '쇼핑',
    blurb: 'Ask prices, find another size, and pay.',
    items: [
      it('이거얼마예요', '이거 얼마예요?', 'How much is this?'),
      it('너무비싸요', '너무 비싸요.', 'It is too expensive.'),
      it('싸요', '싸요.', 'It is cheap.'),
      it('깎아주세요', '좀 깎아 주세요.', 'Please give me a discount.'),
      it('더큰거있어요', '더 큰 거 있어요?', 'Do you have a bigger one?'),
      it('더작은거있어요', '더 작은 거 있어요?', 'Do you have a smaller one?'),
      it('카드로할게요', '카드로 할게요.', 'I will pay by card.'),
      it('봉투주세요', '봉투 주세요.', 'A bag, please.'),
    ],
    steps: [
      tc(
        'How much is it?',
        ['얼마예요? means "how much is it?". Combine with 이거: 이거 얼마예요? The answer uses Sino-Korean numbers (lesson 1.6): 이만 오천 원이에요 ("25,000 won").', '너무 비싸요 means "it is too expensive". 싸요 means "it is cheap".'],
        'Ang 얼마예요 ay "magkano?" Ang sagot ay Sino-Korean: 오천 원 (5,000 won). Ang 너무 비싸요 ay "Ang mahal naman!" at 싸요 ay "mura".',
        'Maghintay para sa number sa display kung hindi mo narinig. Karamihan ng tindahan ay may calculator o screen.',
        '얼마 = "eolma" = "ilan ang halaga". 비싸요 = "bissa" parang "biss-ayy": "ang mahal, ayy!"',
        [
          { ko: '이거 얼마예요?', en: 'How much is this?', rom: 'igeo eolmayeyo' },
          { ko: '너무 비싸요.', en: 'It is too expensive.', rom: 'neomu bissayo' },
          { ko: '싸요.', en: 'It is cheap.', rom: 'ssayo' },
        ],
      ),
      tc(
        'Asking for something else',
        ['더 큰 거 있어요? means "do you have a bigger one?". 더 작은 거 있어요? asks for a smaller one. 더 means "more".', '좀 깎아 주세요 ("please give me a discount") works in markets. In department stores prices are fixed.'],
        'Ang 더 ay "mas" o "pa". 더 큰 거 있어요? = "May mas malaki ba?" Sa palengke (market) lang puwedeng humingi ng tawad: 좀 깎아 주세요.',
        'Sa malalaking tindahan, fixed ang presyo. Hindi magandang humingi ng tawad doon.',
        '더 = "deo" parang "dagdag". Dagdag na laki o liit.',
        [
          { ko: '더 큰 거 있어요?', en: 'Do you have a bigger one?', rom: 'deo keun geo isseoyo' },
          { ko: '더 작은 거 있어요?', en: 'Do you have a smaller one?', rom: 'deo jageun geo isseoyo' },
          { ko: '좀 깎아 주세요.', en: 'Please give me a discount.', rom: 'jom kkakka juseyo' },
        ],
      ),
      tc(
        'Paying',
        ['To pay by card say 카드로 할게요 ("I will do it by card"). 로 means "by means of". Ask for a bag with 봉투 주세요.', 'In Korean shops a plastic bag is not free. You usually pay a small fee.'],
        'Ang 카드로 할게요 ay "Card na lang po." Ang 로 ay "gamit ang". 봉투 주세요 = "Paabot po ng bag." May bayad ito sa maraming tindahan.',
        'Magdala ng sariling eco bag. Karaniwan sa Korea ang plastic bag ay may bayad, at may ilang tindahan na walang bag talaga.',
        '카드로 = card + 로 (using). Parang "sa pamamagitan ng card".',
        [
          { ko: '카드로 할게요.', en: 'I will pay by card.', rom: 'kadeuro halgeyo' },
          { ko: '봉투 주세요.', en: 'A bag, please.', rom: 'bongtu juseyo' },
        ],
      ),
      ch('How do you ask "How much is this?"', '이거 얼마예요?', ['이거 뭐예요?', '이거 있어요?'], '얼마 = how much.', '얼마 = magkano.'),
      ch('The price is too high for you. What do you say?', '너무 비싸요.', ['싸요.', '맛있어요.'], '너무 = too, 비싸요 = expensive.', '너무 = sobra, 비싸요 = mahal.'),
      ch('Which means "Do you have a smaller one?"', '더 작은 거 있어요?', ['더 큰 거 있어요?', '더 싼 거 없어요.'], '작은 = small, 큰 = big.', '작은 = maliit, 큰 = malaki.'),
    ],
  },
  {
    id: '3.6',
    phase: 3,
    title: 'Directions and the subway',
    ko: '길 찾기',
    blurb: 'Ask where things are and get around.',
    items: [
      it('화장실이어디예요', '화장실이 어디예요?', 'Where is the bathroom?'),
      it('지하철역이어디예요', '지하철역이 어디예요?', 'Where is the subway station?'),
      it('오른쪽', '오른쪽', 'right side'),
      it('왼쪽', '왼쪽', 'left side'),
      it('직진', '직진', 'straight ahead'),
      it('몇번출구', '몇 번 출구예요?', 'Which exit number is it?'),
      it('여기에서내려요', '여기에서 내려요.', 'I get off here.'),
      it('갈아타요', '갈아타요.', 'I transfer.'),
    ],
    steps: [
      tc(
        'Where is...?',
        ['어디예요? means "where is it?". Put the place first and add 이/가 (lesson 2.1): 화장실이 어디예요? ("where is the bathroom?"), 지하철역이 어디예요?', 'Learn the directions: 직진 (straight), 오른쪽 (right), 왼쪽 (left).'],
        'Ang 어디예요? ay "Nasaan?" 화장실이 어디예요? = "Nasaan ang CR?" Pinakamahalagang tanong sa biyahe. Para sa direksyon: 직진 (diretso), 오른쪽 (kanan), 왼쪽 (kaliwa).',
        'Turo mo rin ang telepono mo at sabihin 여기 어디예요? ("Nasaan ito?") kung may mapa ka.',
        '화장실 ay isang salita lang. Tandaan ito dahil ito ang una mong kakailanganin: "hwa-jang-sil".',
        [
          { ko: '화장실이 어디예요?', en: 'Where is the bathroom?', rom: 'hwajangsiri eodiyeyo' },
          { ko: '지하철역이 어디예요?', en: 'Where is the subway station?', rom: 'jihacheollyeogi eodiyeyo' },
          { ko: '직진', en: 'straight ahead', rom: 'jikjin' },
          { ko: '오른쪽', en: 'right side', rom: 'oreunjjok' },
          { ko: '왼쪽', en: 'left side', rom: 'oenjjok' },
        ],
      ),
      tc(
        'On the subway',
        ['Station exits are numbered. Ask 몇 번 출구예요? ("which exit number?"). Answer with a Sino-Korean number: 삼 번 출구예요 ("exit 3").', 'Say 여기에서 내려요 ("I get off here") and 갈아타요 ("I transfer") to talk to staff or friends.'],
        'Ang bawat exit ay may numero. Itanong: 몇 번 출구예요? Sagot: 삼 번 출구 = "Exit 3". 내려요 = bababa, 갈아타요 = lilipat ng linya.',
        'I-download ang Naver Map o KakaoMap. Mas kumpleto ang mga ito sa Korea kaysa Google Maps, na limitado ang direksyon doon.',
        '출구 = "chulgu" = "labasan". Parang "chu! labas!" Exit.',
        [
          { ko: '몇 번 출구예요?', en: 'Which exit number is it?', rom: 'myeot beon chulguyeyo' },
          { ko: '여기에서 내려요.', en: 'I get off here.', rom: 'yeogieseo naeryeoyo' },
          { ko: '갈아타요.', en: 'I transfer.', rom: 'garatayo' },
        ],
      ),
      ch('You need the bathroom. What do you ask?', '화장실이 어디예요?', ['화장실이 뭐예요?', '화장실이 있어요.'], '어디 = where.', '어디 = saan.'),
      ch('What does 오른쪽 mean?', 'right side', ['left side', 'straight'], '오른쪽 is right, 왼쪽 is left.', '오른쪽 = kanan, 왼쪽 = kaliwa.', { big: '오른쪽' }),
      ch('How do you say "I transfer" on the subway?', '갈아타요.', ['내려요.', '직진.'], '갈아타다 means to transfer.', '갈아타다 = lilipat.'),
    ],
  },
  {
    id: '3.7',
    phase: 3,
    title: 'Everyday small talk',
    ko: '일상 대화',
    blurb: 'How are you, how do you feel, what are you up to.',
    items: [
      it('잘지내요', '잘 지내요?', 'How have you been?'),
      it('오늘뭐해요', '오늘 뭐 해요?', 'What are you doing today?'),
      it('피곤해요', '피곤해요.', 'I am tired.'),
      it('배고파요', '배고파요.', 'I am hungry.'),
      it('배불러요', '배불러요.', 'I am full.'),
      it('바빠요', '바빠요.', 'I am busy.'),
      it('졸려요', '졸려요.', 'I am sleepy.'),
    ],
    steps: [
      tc(
        'How are you?',
        ['Koreans do not say "how are you" like in English. 잘 지내요? ("have you been well?") is used with people you know. A common answer: 네, 잘 지내요.', '밥 먹었어요? ("did you eat?") is also a friendly greeting, like "how are you".'],
        'Ang 잘 지내요? ay "Kumusta ka na?" para sa kakilala. At ang 밥 먹었어요? ay "Kumain ka na ba?" na tunay na pagbati, parang sa atin!',
        'Kapag may nagtanong ng 밥 먹었어요?, sabihin lang 네, 먹었어요 o 아니요, 아직요 ("Hindi pa").',
        'Ang "Kumain ka na ba?" ay pagmamalasakit sa Pilipinas at Korea. Parehong kultura ng pag-aalala sa pagkain.',
        [
          { ko: '잘 지내요?', en: 'How have you been?', rom: 'jal jinaeyo' },
          { ko: '밥 먹었어요?', en: 'Have you eaten?', rom: 'bap meogeosseoyo' },
          { ko: '오늘 뭐 해요?', en: 'What are you doing today?', rom: 'oneul mwo haeyo' },
        ],
      ),
      tc(
        'How you feel',
        ['Feelings are short and easy: 피곤해요 (I am tired), 배고파요 (I am hungry), 배불러요 (I am full), 바빠요 (I am busy), 졸려요 (I am sleepy).', 'Add 너무 ("very / so") in front: 너무 피곤해요.'],
        'Mga salitang pang-araw-araw: pagod (피곤해요), gutom (배고파요), busog (배불러요), busy (바빠요), antok (졸려요). Dagdagan ng 너무 para sa "sobrang".',
        'Ang 배고파요 ay "gutom" at ang 배불러요 ay "busog". Parehong may 배 (tiyan), kaya madaling tandaan.',
        '배 = tiyan. 배고파요 = "tiyan ay walang laman". 배불러요 = "tiyan ay punô".',
        [
          { ko: '피곤해요.', en: 'I am tired.', rom: 'pigonhaeyo' },
          { ko: '배고파요.', en: 'I am hungry.', rom: 'baegopayo' },
          { ko: '배불러요.', en: 'I am full.', rom: 'baebulleoyo' },
          { ko: '바빠요.', en: 'I am busy.', rom: 'bappayo' },
          { ko: '졸려요.', en: 'I am sleepy.', rom: 'jollyeoyo' },
        ],
      ),
      ch('Your friend asks 잘 지내요? What is a natural reply?', '네, 잘 지내요.', ['네, 이거 주세요.', '아니요, 화장실이에요.'], '잘 지내요 is both the question and the answer.', 'Ulitin lang ang 잘 지내요 para sa sagot.'),
      ch('You have not eaten and your stomach is empty. Say it.', '배고파요.', ['배불러요.', '졸려요.'], '배고파요 = I am hungry.', '배고파요 = gutom ako.'),
      ch('What does 피곤해요 mean?', 'I am tired.', ['I am busy.', 'I am full.'], '피곤 means fatigue.', '피곤해요 = pagod ako.', { big: '피곤해요' }),
    ],
  },
  {
    id: '3.8',
    phase: 3,
    title: 'Time and days',
    ko: '시간과 요일',
    blurb: 'What time is it, and what day?',
    items: [
      it('지금몇시예요', '지금 몇 시예요?', 'What time is it now?'),
      it('세시예요', '세 시예요.', 'It is three o\'clock.'),
      it('오늘', '오늘', 'today'),
      it('월요일', '월요일', 'Monday'),
      it('화요일', '화요일', 'Tuesday'),
      it('수요일', '수요일', 'Wednesday'),
      it('목요일', '목요일', 'Thursday'),
      it('금요일', '금요일', 'Friday'),
      it('토요일', '토요일', 'Saturday'),
      it('일요일', '일요일', 'Sunday'),
    ],
    steps: [
      tc(
        'What time is it?',
        ['지금 몇 시예요? means "what time is it now?". The hour uses native numbers + 시: 한 시, 두 시, 세 시. Minutes use Sino-Korean + 분: 십 분, 삼십 분.', '세 시 삼십 분이에요 means "it is 3:30". 반 means "half": 세 시 반.'],
        'Ang oras ay mixed: native number para sa oras (세 시) at Sino-Korean para sa minuto (십 분). Pamilyar ito, parang "alas-tres" at "labinlimang minuto".',
        'Ang 반 ay "kalahati". 세 시 반 = "Alas-tres y medya". Madali!',
        '시 = oras (hour). 분 = minuto. 시 ay "see", 분 ay "boon". Parang "see you in an hour".',
        [
          { ko: '지금 몇 시예요?', en: 'What time is it now?', rom: 'jigeum myeot siyeyo' },
          { ko: '세 시예요.', en: 'It is three o\'clock.', rom: 'se siyeyo' },
          { ko: '세 시 반이에요.', en: 'It is half past three.', rom: 'se si banieyo' },
        ],
      ),
      tc(
        'Days of the week',
        ['The days come from the sun, moon and five elements: 월 (moon), 화 (fire), 수 (water), 목 (wood), 금 (metal), 토 (earth), 일 (sun). Add 요일 to each.', '오늘 무슨 요일이에요? means "what day is it today?".'],
        'Lahat ng araw ay may 요일. Ito ay nakabase sa moon, fire, water, wood, metal, earth, sun. Madaling tandaan kapag alam mo ang kahulugan.',
        'Ang 일요일 ay Linggo at ang 일 ay "sun" din, kaya makikita mo ang pattern: Sunday = sun day sa English din.',
        '월화수목금토일 ay ginagamit sa kalendaryo. Gumawa ng kanta o tula: wol-hwa-su-mok-geum-to-il.',
        [
          { ko: '월요일', en: 'Monday', rom: 'woryoil' },
          { ko: '화요일', en: 'Tuesday', rom: 'hwayoil' },
          { ko: '수요일', en: 'Wednesday', rom: 'suyoil' },
          { ko: '목요일', en: 'Thursday', rom: 'mogyoil' },
          { ko: '금요일', en: 'Friday', rom: 'geumyoil' },
          { ko: '토요일', en: 'Saturday', rom: 'toyoil' },
          { ko: '일요일', en: 'Sunday', rom: 'iryoil' },
        ],
      ),
      ch('Which number system do you use for the hour in "three o\'clock"?', 'Native Korean (세 시)', ['Sino-Korean (삼 시)'], 'Hours use native numbers; minutes use Sino-Korean.', 'Oras = native number. Minuto = Sino-Korean.'),
      ch('What does 토요일 mean?', 'Saturday', ['Sunday', 'Thursday'], '토 is earth, 토요일 is Saturday.', '토요일 = Sabado.', { big: '토요일' }),
      ch('How do you ask "What time is it?"', '지금 몇 시예요?', ['오늘 무슨 요일이에요?', '이거 얼마예요?'], '몇 시 = what time.', '몇 시 = anong oras.'),
    ],
  },
  {
    id: '3.9',
    phase: 3,
    title: 'Making plans',
    ko: '약속',
    blurb: 'Invite a friend and agree on a time.',
    items: [
      it('같이영화볼까요', '같이 영화 볼까요?', 'Shall we watch a movie together?'),
      it('좋아요', '좋아요.', 'Sounds good.'),
      it('몇시에만날까요', '몇 시에 만날까요?', 'What time shall we meet?'),
      it('어디에서만날까요', '어디에서 만날까요?', 'Where shall we meet?'),
      it('이번주말에시간있어요', '이번 주말에 시간 있어요?', 'Are you free this weekend?'),
      it('미안해요시간없어요', '미안해요. 시간 없어요.', 'Sorry. I have no time.'),
    ],
    steps: [
      tc(
        'Shall we...?',
        ['Add -(으)ㄹ까요? to a verb stem to say "shall we...?". Vowel stem + ㄹ까요: 볼까요 (from 보다), 갈까요 (from 가다). Consonant stem + 을까요: 먹을까요.', '같이 means "together". 같이 영화 볼까요? "Shall we watch a movie together?"'],
        'Ang -(으)ㄹ까요? ay "Tara, ..." o "Gusto mo bang...?" Parehong rule sa 거예요 at 수 있어요: ㄹ kung vowel, 을 kung consonant. 같이 = sabay-sabay.',
        'Ito ang pinakamagandang paraan para mag-imbita. Magalang pero friendly.',
        '-ㄹ까요 ay "ll-kka-yo": parang "tara na, ka-yo?" Isipin mong tinatanong mo ang "ka-yo" (kayo).',
        [
          { ko: '같이 영화 볼까요?', en: 'Shall we watch a movie together?', rom: 'gachi yeonghwa bolkkayo' },
          { ko: '같이 먹을까요?', en: 'Shall we eat together?', rom: 'gachi meogeulkkayo' },
          { ko: '좋아요.', en: 'Sounds good.', rom: 'joayo' },
        ],
      ),
      tc(
        'Arranging time and place',
        ['Ask when with 몇 시에 만날까요? ("what time shall we meet?") and where with 어디에서 만날까요?', 'To check someone is free: 이번 주말에 시간 있어요? To refuse politely: 미안해요, 시간 없어요.'],
        'Ang 몇 시에 ay "anong oras" at ang 어디에서 ay "saan". Para sa pag-check ng schedule: 이번 주말에 시간 있어요? (Free ka ba ngayong weekend?) Kung hindi kaya: 미안해요, 시간 없어요.',
        'Ang 미안해요 ay isang malambot na "sorry". Sa mga magulang o nakatatanda, gamitin ang 죄송합니다.',
        '만날까요 = 만나다 (meet) + ㄹ까요. Sa Tagalog: "magkita kaya tayo?"',
        [
          { ko: '이번 주말에 시간 있어요?', en: 'Are you free this weekend?', rom: 'ibeon jumare sigan isseoyo' },
          { ko: '몇 시에 만날까요?', en: 'What time shall we meet?', rom: 'myeot sie mannalkkayo' },
          { ko: '어디에서 만날까요?', en: 'Where shall we meet?', rom: 'eodieseo mannalkkayo' },
          { ko: '미안해요. 시간 없어요.', en: 'Sorry. I have no time.', rom: 'mianhaeyo. sigan eopseoyo' },
        ],
      ),
      ch('Which means "Shall we eat together?"', '같이 먹을까요?', ['같이 먹었어요.', '같이 먹고 싶어요.'], '먹 + 을까요 = shall we eat.', '먹 + 을까요 = tara, kain tayo.'),
      ch('Make "shall we go?" from 가다.', '갈까요?', ['가을까요?', '가까요?'], '가 ends in a vowel, so ㄹ까요: 갈까요.', 'Walang batchim ang 가, kaya ㄹ lang: 갈까요.'),
      ch('You cannot come. How do you say sorry politely?', '미안해요. 시간 없어요.', ['좋아요. 같이 가요.', '잘 먹겠습니다.'], '미안해요 + 시간 없어요 = sorry, no time.', '미안해요 + 시간 없어요 = pasensya, wala akong oras.'),
    ],
  },
  {
    id: '3.10',
    phase: 3,
    title: 'Talking about your weekend',
    ko: '주말 이야기',
    blurb: 'Say what you did and how it was.',
    items: [
      it('주말에뭐했어요', '주말에 뭐 했어요?', 'What did you do over the weekend?'),
      it('친구를만났어요', '친구를 만났어요.', 'I met a friend.'),
      it('집에서쉬었어요', '집에서 쉬었어요.', 'I rested at home.'),
      it('영화를봤어요', '영화를 봤어요.', 'I watched a movie.'),
      it('재미있었어요', '재미있었어요.', 'It was fun.'),
      it('좋았어요', '좋았어요.', 'It was good.'),
    ],
    steps: [
      tc(
        'What did you do?',
        ['주말에 뭐 했어요? means "what did you do on the weekend?". It uses the past tense you learned in 2.6. 에 marks the time.', 'Common answers: 친구를 만났어요 (I met a friend), 영화를 봤어요 (I watched a movie), 집에서 쉬었어요 (I rested at home).'],
        'Gamit mo na ang past tense (2.6), 에 (2.5), 을/를 (2.2), at 에서 (2.5). Ang 주말에 뭐 했어요? ay "Anong ginawa mo nitong weekend?"',
        'Ang 쉬다 ay "magpahinga". Maraming Koreano ang sasabihin 집에서 쉬었어요 at okay lang iyon.',
        '쉬었어요 = 쉬다 + 었어요. Dalawang ㅆ ay hindi kailangan; isa lang ang ㅆ sa dulo.',
        [
          { ko: '주말에 뭐 했어요?', en: 'What did you do on the weekend?', rom: 'jumare mwo haesseoyo' },
          { ko: '친구를 만났어요.', en: 'I met a friend.', rom: 'chingureul mannasseoyo' },
          { ko: '집에서 쉬었어요.', en: 'I rested at home.', rom: 'jibeseo swieosseoyo' },
          { ko: '영화를 봤어요.', en: 'I watched a movie.', rom: 'yeonghwareul bwasseoyo' },
        ],
      ),
      tc(
        'How was it?',
        ['Describe it with a past-tense adjective: 재미있었어요 (it was fun), 좋았어요 (it was good). They follow the same -았/었어요 rule.', 'Combine with 그리고 (2.9): 영화를 봤어요. 그리고 재미있었어요.'],
        'Ang 재미있었어요 ay "Nakakatuwa/Masaya iyon." 좋았어요 = "Maganda iyon." Ang rule ay pareho: 좋 → 좋았어요, 재미있 → 재미있었어요.',
        'Ang 재미있어요 ay "masaya o nakakaaliw". Ginagamit sa pelikula, laro, at kaibigan.',
        '재미 = "jaemi" = "kasiyahan". Parang "jam-mee": jam ng saya.',
        [
          { ko: '재미있었어요.', en: 'It was fun.', rom: 'jaemiisseosseoyo' },
          { ko: '좋았어요.', en: 'It was good.', rom: 'joasseoyo' },
          { ko: '영화를 봤어요. 재미있었어요.', en: 'I watched a movie. It was fun.' },
        ],
      ),
      ch('How do you say "I rested at home"?', '집에서 쉬었어요.', ['집에 쉬어요.', '집에서 쉴 거예요.'], '집에서 = at home (action place), 쉬었어요 = rested (past).', '집에서 = sa bahay (may ginagawa), 쉬었어요 = nagpahinga.'),
      ch('What does 재미있었어요 mean?', 'It was fun.', ['It was expensive.', 'I am tired.'], '재미있다 means fun.', '재미있었어요 = masaya iyon.', { big: '재미있었어요' }),
      ch('Which sentence says "I met a friend"?', '친구를 만났어요.', ['친구를 만날 거예요.', '친구를 만나고 싶어요.'], '만났어요 is past, 만날 거예요 is future.', '만났어요 = past (nakipagkita). 만날 거예요 = future.'),
    ],
  },
  {
    id: '3.11',
    phase: 3,
    title: 'Asking for help',
    ko: '도움 요청',
    blurb: 'When you are lost, sick, or cannot communicate.',
    items: [
      it('도와주세요', '도와주세요.', 'Please help me.'),
      it('길을잃었어요', '길을 잃었어요.', 'I am lost.'),
      it('아파요', '아파요.', 'It hurts / I am sick.'),
      it('병원', '병원', 'hospital'),
      it('영어할수있어요', '영어 할 수 있어요?', 'Can you speak English?'),
      it('한국어조금해요', '한국어를 조금 해요.', 'I speak a little Korean.'),
      it('이거뭐예요', '이거 뭐예요?', 'What is this?'),
    ],
    steps: [
      tc(
        'Emergency words',
        ['도와주세요 means "please help me". 길을 잃었어요 means "I am lost". 아파요 means "it hurts / I am sick". 병원 is "hospital".', 'In an emergency in Korea call 119 for ambulance and fire, 112 for police.'],
        'Ang 도와주세요 ay "Tulungan niyo po ako!" Ang 길을 잃었어요 ay "Naliligaw ako." Ang 아파요 ay "Masakit" o "May sakit ako." Ang 병원 ay "ospital".',
        'Sa emergency, tumawag sa 119 (ambulansya/bumbero) o 112 (pulis). May English interpreter sa maraming serbisyo.',
        '아파요 = "apa-yo" = "aray-yo!" Parang "aray" sa Tagalog, madaling tandaan.',
        [
          { ko: '도와주세요.', en: 'Please help me.', rom: 'dowajuseyo' },
          { ko: '길을 잃었어요.', en: 'I am lost.', rom: 'gireul ireosseoyo' },
          { ko: '아파요.', en: 'It hurts / I am sick.', rom: 'apayo' },
          { ko: '병원', en: 'hospital', rom: 'byeongwon' },
        ],
      ),
      tc(
        'Using your Korean level honestly',
        ['Use 수 있어요 (lesson 2.10) to ask 영어 할 수 있어요? ("can you speak English?"). Say 한국어를 조금 해요 ("I speak a little Korean").', 'Koreans appreciate the effort. A little Korean often gets a warm response.'],
        'Ang 영어 할 수 있어요? ay "Marunong ka bang mag-English?" Ang 한국어를 조금 해요 ay "Kaunti lang ang Korean ko." Pinapahalagahan ito ng mga Koreano.',
        'Magsimula sa Korean at lumipat sa English kung kailangan. Mas magiliw ang pakiramdam sa kausap.',
        '조금 = "jogeum" = "kaunti". Parang "jo-gum" = "jo-konti".',
        [
          { ko: '영어 할 수 있어요?', en: 'Can you speak English?', rom: 'yeongeo hal su isseoyo' },
          { ko: '한국어를 조금 해요.', en: 'I speak a little Korean.', rom: 'hangugeoreul jogeum haeyo' },
          { ko: '이거 뭐예요?', en: 'What is this?', rom: 'igeo mwoyeyo' },
        ],
      ),
      ch('You are lost. What do you say?', '길을 잃었어요.', ['길이 좋아요.', '길을 먹었어요.'], '길 = road, 잃었어요 = lost.', '길 = daan, 잃었어요 = nawala.'),
      ch('You want to ask "Can you speak English?"', '영어 할 수 있어요?', ['영어 먹을 수 있어요?', '영어 할 거예요?'], '할 수 있어요 = can do (lesson 2.10).', '할 수 있어요 = kaya (2.10).'),
      ch('What does 아파요 mean?', 'It hurts / I am sick.', ['I am hungry.', 'I am lost.'], '아프다 is to be in pain or ill.', '아파요 = masakit / may sakit.', { big: '아파요' }),
    ],
  },
  {
    id: '3.12',
    phase: 3,
    title: 'Social phrases',
    ko: '사회적 표현',
    blurb: 'Small words that make you sound polite and warm.',
    items: [
      it('실례합니다', '실례합니다.', 'Excuse me.'),
      it('고마워요', '고마워요.', 'Thanks.'),
      it('천만에요', '천만에요.', 'You are welcome.'),
      it('미안해요', '미안해요.', 'Sorry.'),
      it('축하해요', '축하해요.', 'Congratulations.'),
      it('건배', '건배!', 'Cheers!'),
      it('맛있게드세요', '맛있게 드세요.', 'Enjoy your meal.'),
      it('화이팅', '화이팅!', 'You can do it!'),
    ],
    steps: [
      tc(
        'Excuse me, thanks, sorry',
        ['실례합니다 means "excuse me" when you pass or enter a room. 고마워요 is a warm "thanks", softer than 감사합니다. 천만에요 means "you are welcome".', '미안해요 is "sorry" for friends and equals. For elders or formal settings use 죄송합니다 (lesson 1.1).'],
        'Ang 실례합니다 ay "Excuse me po." Ang 고마워요 ay "Salamat," hindi gaanong pormal sa 감사합니다. 천만에요 = "Walang anuman."',
        'Pumili base sa kausap. Mas matanda o hindi kakilala: 감사합니다, 죄송합니다. Kaibigan: 고마워요, 미안해요.',
        '고마워요 = "gomawoyo" = "go-ma-wo". Isipin mo: "Go! Ma, wo!" = "Salamat, Ma!"',
        [
          { ko: '실례합니다.', en: 'Excuse me.', rom: 'sillyehamnida' },
          { ko: '고마워요.', en: 'Thanks.', rom: 'gomawoyo' },
          { ko: '천만에요.', en: 'You are welcome.', rom: 'cheonmaneyo' },
          { ko: '미안해요.', en: 'Sorry.', rom: 'mianhaeyo' },
        ],
      ),
      tc(
        'Celebrating and cheering',
        ['축하해요 means "congratulations". 건배! means "cheers!". 맛있게 드세요 is what a host says to guests: "enjoy your meal". 화이팅! ("fighting!") means "you can do it!".', 'Reply to 맛있게 드세요 with 잘 먹겠습니다 (lesson 3.3).'],
        'Ang 축하해요 ay "Congrats!" Ang 건배 ay "Cheers!" Ang 화이팅! ay "Kaya mo yan!", ginagamit bago exam, laro, o trabaho.',
        'Kapag may nag-imbita sa iyo, ang unang sagot ay 잘 먹겠습니다 pagkaabot ng pagkain.',
        '화이팅 ay hiram sa English na "fighting". Madaling tandaan, at nababasa mo na.',
        [
          { ko: '축하해요.', en: 'Congratulations.', rom: 'chukahaeyo' },
          { ko: '건배!', en: 'Cheers!', rom: 'geonbae' },
          { ko: '맛있게 드세요.', en: 'Enjoy your meal.', rom: 'masitge deuseyo' },
          { ko: '화이팅!', en: 'You can do it!', rom: 'hwaiting' },
        ],
      ),
      ch('Someone says 감사합니다. What is a natural reply?', '천만에요.', ['실례합니다.', '건배!'], '천만에요 means "you are welcome".', '천만에요 = walang anuman.'),
      ch('A friend passed their exam. What do you say?', '축하해요.', ['미안해요.', '실례합니다.'], '축하 means congratulations.', '축하해요 = congrats.'),
      ch('You bump into someone on a crowded subway. What do you say?', '실례합니다.', ['고마워요.', '화이팅!'], '실례합니다 is the standard "excuse me".', '실례합니다 = excuse me po.', { speak: '실례합니다' }),
    ],
  },
];

export const UPCOMING_EVERYDAY: { id: string; title: string; ko: string }[] = [];
