import type { Lesson } from './lessons';

export const MORE3: Lesson[] = [
  {
    id: '2.5',
    phase: 2,
    title: 'Places: 에 vs 에서',
    ko: '에 / 에서',
    blurb: 'Going to a place versus doing something at a place.',
    items: [
      { id: 'w.학교', korean: '학교', english: 'school' },
      { id: 'w.집', korean: '집', english: 'house, home' },
      { id: 'w.카페', korean: '카페', english: 'cafe' },
      { id: 's.학교에가요', korean: '학교에 가요.', english: 'I go to school.' },
      { id: 's.카페에서공부해요', korean: '카페에서 공부해요.', english: 'I study at a cafe.' },
    ],
    steps: [
      {
        kind: 'teach',
        title: '에: a destination or a place where something exists',
        body: [
          '에 marks where you are going, or where something is: 학교에 가요 (I go to school), 집에 있어요 (I am at home).',
          'Use it with verbs of movement (가다, 오다) and existence (있다, 없다).',
        ],
        tl: ['Ang 에 ay "sa" o "papunta sa". 학교에 가요 = "Pumupunta ako sa school." 집에 있어요 = "Nasa bahay ako."'],
        tip: 'Parehong 에 ang gamit sa oras: 일곱 시에 (at 7 o\'clock). Pero sa ngayon, ang lugar muna.',
        remember: 'Ang 에 ay pinakamaikli, kaya para sa pinakasimpleng ideya: punta o nandoon.',
        phrases: [
          { ko: '학교에 가요.', en: 'I go to school.', rom: 'hakgyoe gayo' },
          { ko: '집에 있어요.', en: 'I am at home.', rom: 'jibe isseoyo' },
        ],
      },
      {
        kind: 'teach',
        title: '에서: where an action happens',
        body: [
          '에서 marks the place where you do an action: 카페에서 공부해요 (I study at a cafe), 집에서 먹어요 (I eat at home).',
          'The test: is there an action verb like study, eat, work? Use 에서. Is it moving to a place or existing there? Use 에.',
        ],
        tl: ['Ang 에서 ay "sa" din, pero kung saan ginagawa ang kilos. 카페에서 공부해요 = "Nag-aaral ako sa cafe."'],
        tip: 'Tanong: "May ginagawa ba?" Oo → 에서. "Pupunta lang o nandoon?" → 에.',
        remember: '에서 ay mas mahaba kaysa 에 dahil mas mahaba ang kilos: may "ginagawa".',
        phrases: [
          { ko: '카페에서 공부해요.', en: 'I study at a cafe.', rom: 'kapeeseo gongbuhaeyo' },
          { ko: '회사에서 일해요.', en: 'I work at a company.', rom: 'hoesaeseo ilhaeyo' },
        ],
      },
      {
        kind: 'choice',
        prompt: '저는 학교___ 가요. (I go to school.)',
        options: ['에', '에서'],
        answer: '에',
        why: '가요 is a movement verb, so 에 marks the destination.',
        whyTl: 'Punta (가요) = destination, kaya 에.',
      },
      {
        kind: 'choice',
        prompt: '저는 카페___ 공부해요. (I study at a cafe.)',
        options: ['에', '에서'],
        answer: '에서',
        why: '공부해요 is an action done at the cafe, so 에서.',
        whyTl: 'Ang 공부해요 ay kilos na ginagawa sa cafe, kaya 에서.',
      },
      {
        kind: 'choice',
        prompt: '집___ 있어요. (I am at home.)',
        options: ['에', '에서'],
        answer: '에',
        why: '있어요 shows existence, so 에.',
        whyTl: '있어요 = nandoon lang, kaya 에.',
      },
    ],
  },
  {
    id: '2.6',
    phase: 2,
    title: 'Past tense: -았어요 / -었어요',
    ko: '과거',
    blurb: 'Talking about what already happened.',
    items: [
      { id: 'v.갔어요', korean: '갔어요', english: 'went' },
      { id: 'v.먹었어요', korean: '먹었어요', english: 'ate' },
      { id: 'v.봤어요', korean: '봤어요', english: 'saw / watched' },
      { id: 'v.했어요', korean: '했어요', english: 'did' },
      { id: 'w.어제', korean: '어제', english: 'yesterday' },
      { id: 's.어제영화를봤어요', korean: '어제 영화를 봤어요.', english: 'I watched a movie yesterday.' },
    ],
    steps: [
      {
        kind: 'teach',
        title: 'Same rule, with ㅆ',
        body: [
          'The past tense follows the same bright / dark vowel rule as the present: stem + 았어요 (bright ㅏ ㅗ) or 었어요 (everything else). 하다 becomes 했어요.',
          'Vowel stems contract: 가 + 았어요 = 갔어요. 보 + 았어요 = 봤어요. 마시 + 었어요 = 마셨어요.',
        ],
        tl: ['Halos pareho sa present, may dagdag lang na ㅆ. 먹어요 → 먹었어요. 가요 → 갔어요. 공부해요 → 공부했어요. Tandaan ang ㅆ: iyon ang past marker.'],
        tip: 'Hanapin ang ㅆ sa dulo ng verb. Kapag nakita mo ang ㅆ, past na iyon.',
        remember: 'Ang ㅆ ay parang "tapos na": doble, na parang dalawang beses nang nangyari.',
        phrases: [
          { ko: '먹었어요', en: 'ate', rom: 'meogeosseoyo' },
          { ko: '갔어요', en: 'went', rom: 'gasseoyo' },
          { ko: '봤어요', en: 'saw, watched', rom: 'bwasseoyo' },
          { ko: '했어요', en: 'did', rom: 'haesseoyo' },
        ],
      },
      {
        kind: 'teach',
        title: 'Time words and a full sentence',
        body: [
          '어제 means yesterday. Time words usually come near the start of the sentence.',
          '어제 영화를 봤어요: "I watched a movie yesterday." Notice the pattern: time, object + 를, verb.',
        ],
        tl: ['Ang time word ay nasa unahan: "Kahapon, pelikula, napanood." Walang kailangang baguhin sa ibang bahagi, ang verb lang ang may ㅆ.'],
        tip: 'Hindi mo kailangan ng "ako" sa Korean. 어제 영화를 봤어요 ay buo na.',
        remember: '어제 영화 = "Kahapon, movie". Madaling tandaan dahil parang pamagat ng pelikula.',
        phrases: [
          { ko: '어제 영화를 봤어요.', en: 'I watched a movie yesterday.' },
          { ko: '어제 김치를 먹었어요.', en: 'I ate kimchi yesterday.' },
        ],
      },
      {
        kind: 'choice',
        prompt: 'Make the past of 먹다 (stem 먹).',
        options: ['먹았어요', '먹었어요', '먹어써요'],
        answer: '먹었어요',
        why: 'ㅓ is a dark vowel, so 었어요.',
        whyTl: 'Dark vowel (ㅓ) kaya 었어요.',
      },
      {
        kind: 'choice',
        prompt: 'Make the past of 가다 (stem 가).',
        options: ['갔어요', '가었어요', '가아요'],
        answer: '갔어요',
        why: '가 + 았어요 contracts to 갔어요.',
        whyTl: '가 + 았어요 = 갔어요.',
      },
      {
        kind: 'choice',
        prompt: 'What is the past of 공부해요?',
        options: ['공부했어요', '공부하었어요', '공부해써요'],
        answer: '공부했어요',
        why: 'Every 하다 verb becomes 했어요 in the past.',
        whyTl: 'Lahat ng 하다 ay 했어요 sa past.',
      },
      {
        kind: 'choice',
        prompt: 'What does 어제 영화를 봤어요 mean?',
        big: '어제 영화를 봤어요',
        options: ['I watched a movie yesterday.', 'I will watch a movie tomorrow.', 'I like movies.'],
        answer: 'I watched a movie yesterday.',
        why: '어제 = yesterday, 봤어요 = watched (past).',
        whyTl: '어제 = kahapon, 봤어요 = napanood.',
      },
    ],
  },
  {
    id: '2.7',
    phase: 2,
    title: 'Wanting: -고 싶어요',
    ko: '-고 싶어요',
    blurb: 'Saying what you want to do.',
    items: [
      { id: 's.한국에가고싶어요', korean: '한국에 가고 싶어요.', english: 'I want to go to Korea.' },
      { id: 's.먹고싶어요', korean: '먹고 싶어요.', english: 'I want to eat.' },
      { id: 's.마시고싶어요', korean: '커피를 마시고 싶어요.', english: 'I want to drink coffee.' },
    ],
    steps: [
      {
        kind: 'teach',
        title: 'Stem + 고 싶어요',
        body: [
          'Remove 다 from the verb and add 고 싶어요. 가다 → 가고 싶어요 (I want to go). 먹다 → 먹고 싶어요 (I want to eat).',
          'This one is easy: no vowel rules, no contractions.',
        ],
        tl: ['Isa ito sa pinakamadaling pattern. Stem + 고 싶어요 = "gusto kong...". Walang ibang rule: 가고 싶어요, 먹고 싶어요, 공부하고 싶어요.'],
        tip: 'Gamitin ito para sa sarili mo at sa tanong na "Gusto mo ba...?" Hindi ito karaniwang ginagamit para sa iba, kasi hindi mo alam ang nasa isip nila.',
        remember: '싶 ay parang "sip": gusto mong humigop, gusto mong gawin.',
        phrases: [
          { ko: '가고 싶어요.', en: 'I want to go.', rom: 'gago sipeoyo' },
          { ko: '먹고 싶어요.', en: 'I want to eat.', rom: 'meokgo sipeoyo' },
          { ko: '공부하고 싶어요.', en: 'I want to study.', rom: 'gongbuhago sipeoyo' },
        ],
      },
      {
        kind: 'teach',
        title: 'Full wishes',
        body: ['Combine it with places and objects you already know.'],
        tl: ['Pagsamahin ang mga natutunan mo na: 한국에 가고 싶어요 = "Gusto kong pumunta sa Korea."'],
        tip: 'Para magtanong: 뭐 먹고 싶어요? ("Ano ang gusto mong kainin?")',
        remember: 'Verb sa dulo pa rin! Ang 싶어요 ang nasa dulo, hindi ang 가고.',
        phrases: [
          { ko: '한국에 가고 싶어요.', en: 'I want to go to Korea.' },
          { ko: '커피를 마시고 싶어요.', en: 'I want to drink coffee.' },
          { ko: '뭐 먹고 싶어요?', en: 'What do you want to eat?' },
        ],
      },
      {
        kind: 'choice',
        prompt: 'How do you say "I want to eat"?',
        options: ['먹고 싶어요', '먹어요 싶어요', '먹고 싶이에요'],
        answer: '먹고 싶어요',
        why: 'Stem 먹 + 고 싶어요.',
        whyTl: 'Stem 먹 + 고 싶어요.',
      },
      {
        kind: 'choice',
        prompt: 'What does 한국에 가고 싶어요 mean?',
        big: '한국에 가고 싶어요',
        options: ['I want to go to Korea.', 'I went to Korea.', 'I am Korean.'],
        answer: 'I want to go to Korea.',
        why: '한국에 = to Korea, 가고 싶어요 = want to go.',
        whyTl: '한국에 = sa Korea, 가고 싶어요 = gustong pumunta.',
      },
      {
        kind: 'choice',
        prompt: 'What does 뭐 먹고 싶어요? ask?',
        options: ['What do you want to eat?', 'What did you eat?', 'Where do you eat?'],
        answer: 'What do you want to eat?',
        why: '뭐 = what, 먹고 싶어요 = want to eat.',
        whyTl: '뭐 + 먹고 싶어요 = "Ano ang gusto mong kainin?"',
      },
    ],
  },
  {
    id: '2.8',
    phase: 2,
    title: 'Future and plans: -(으)ㄹ 거예요',
    ko: '-(으)ㄹ 거예요',
    blurb: 'What you are going to do.',
    items: [
      { id: 'w.내일', korean: '내일', english: 'tomorrow' },
      { id: 'w.만나다', korean: '만나요', english: 'meet' },
      { id: 's.내일친구를만날거예요', korean: '내일 친구를 만날 거예요.', english: 'I will meet a friend tomorrow.' },
      { id: 's.갈거예요', korean: '갈 거예요.', english: 'I will go.' },
    ],
    steps: [
      {
        kind: 'teach',
        title: 'Vowel stem + ㄹ 거예요, consonant stem + 을 거예요',
        body: [
          'After a vowel stem, add ㄹ 거예요: 가 → 갈 거예요 (I will go). The ㄹ attaches to the last block as batchim.',
          'After a consonant stem, add 을 거예요: 먹 → 먹을 거예요 (I will eat). For 하다 verbs: 할 거예요.',
        ],
        tl: ['Ito ang "gagawin ko" o "mangyayari". Walang batchim ang stem? Dagdagan ng ㄹ 거예요. May batchim? 을 거예요. 하다 → 할 거예요.'],
        tip: 'Ang 거예요 ay literal na "ito ay bagay": "ang bagay na gagawin ko". Kaya ang -(으)ㄹ 거예요 ay isang "plano" o "hula".',
        remember: 'Parehong rule sa 은/는 at 이/가: batchim → mas mahaba (을), walang batchim → mas maikli (ㄹ).',
        phrases: [
          { ko: '갈 거예요.', en: 'I will go.', rom: 'gal geoyeyo' },
          { ko: '먹을 거예요.', en: 'I will eat.', rom: 'meogeul geoyeyo' },
          { ko: '할 거예요.', en: 'I will do.', rom: 'hal geoyeyo' },
        ],
      },
      {
        kind: 'teach',
        title: 'Putting plans together',
        body: [
          '내일 means tomorrow. 만나다 (to meet) is a vowel stem, so: 만날 거예요.',
          '내일 친구를 만날 거예요: "I will meet a friend tomorrow."',
        ],
        tl: ['내일 = bukas. 만나다 + ㄹ 거예요 = 만날 거예요. "Bukas, kaibigan, makikipagkita."'],
        tip: 'Ang -(으)ㄹ 거예요 ay maaaring "Siguro" din depende sa tono. Para sa plano, gamitin ang oras: 내일, 주말에.',
        remember: '내일 (naeil) ay parang "nay-il": "bukas, may ilan pa tayong gagawin".',
        phrases: [
          { ko: '내일 친구를 만날 거예요.', en: 'I will meet a friend tomorrow.' },
          { ko: '내일 학교에 갈 거예요.', en: 'I will go to school tomorrow.' },
        ],
      },
      {
        kind: 'choice',
        prompt: 'Make "I will eat" from 먹다.',
        options: ['먹을 거예요', '먹ㄹ 거예요', '먹 거예요'],
        answer: '먹을 거예요',
        why: '먹 ends in a consonant, so 을 거예요.',
        whyTl: 'May batchim ang 먹, kaya 을 거예요.',
      },
      {
        kind: 'choice',
        prompt: 'Make "I will go" from 가다.',
        options: ['갈 거예요', '가을 거예요', '가 거예요'],
        answer: '갈 거예요',
        why: '가 ends in a vowel, so ㄹ attaches to it: 갈.',
        whyTl: 'Walang batchim ang 가, kaya ㄹ lang: 갈.',
      },
      {
        kind: 'choice',
        prompt: 'What does 내일 학교에 갈 거예요 mean?',
        big: '내일 학교에 갈 거예요',
        options: ['I will go to school tomorrow.', 'I went to school yesterday.', 'I want to go to school.'],
        answer: 'I will go to school tomorrow.',
        why: '내일 = tomorrow, 갈 거예요 = will go.',
        whyTl: '내일 = bukas, 갈 거예요 = pupunta.',
      },
    ],
  },
  {
    id: '2.9',
    phase: 2,
    title: 'Linking: -고, 그리고, 그런데',
    ko: '-고 / 그리고 / 그런데',
    blurb: 'Joining ideas into longer sentences.',
    items: [
      { id: 's.밥을먹고커피를마셨어요', korean: '밥을 먹고 커피를 마셨어요.', english: 'I ate and then drank coffee.' },
      { id: 'w.그리고', korean: '그리고', english: 'and, and then' },
      { id: 'w.그런데', korean: '그런데', english: 'but, by the way' },
    ],
    steps: [
      {
        kind: 'teach',
        title: 'Joining verbs with -고',
        body: [
          'Attach 고 to a verb stem to say "and (then)": 밥을 먹고 커피를 마셨어요, "I ate, and then drank coffee".',
          'Only the last verb carries the tense. The first verb stays as the stem + 고.',
        ],
        tl: ['Ang 고 ay "at" o "tapos". Idikit lang sa stem: 먹고, 가고, 공부하고. Ang huling verb lang ang may panahon (past o future).'],
        tip: 'Hindi mo kailangan ng 었 sa unang verb. Isang ㅆ lang, sa dulo.',
        remember: '고 ay parang "go" ng "tapos go!": gawin ang isa, tapos go sa susunod.',
        phrases: [
          { ko: '밥을 먹고 커피를 마셨어요.', en: 'I ate and then drank coffee.' },
          { ko: '공부하고 집에 갔어요.', en: 'I studied and then went home.' },
        ],
      },
      {
        kind: 'teach',
        title: 'Joining sentences',
        body: [
          '그리고 means "and" at the start of a new sentence. 그런데 means "but" or "by the way".',
          'They come at the front: 저는 학생이에요. 그리고 한국어를 공부해요.',
        ],
        tl: ['그리고 = "at" (bagong pangungusap). 그런데 = "pero" o "nga pala". Nasa unahan lang ng pangungusap.'],
        tip: '그런데 ay puwedeng gamitin para magpalit ng paksa, parang "Nga pala,...". Ito ay natural sa usapan.',
        remember: '그런데 ay "geu-reon-de", parang "ang daya naman, pero...". Pero.',
        phrases: [
          { ko: '그리고', en: 'and', rom: 'geurigo' },
          { ko: '그런데', en: 'but, by the way', rom: 'geureonde' },
        ],
      },
      {
        kind: 'choice',
        prompt: 'How do you say "I ate and then went home"?',
        options: ['먹고 집에 갔어요.', '먹었고 집에 갔어요.', '먹어요고 집에 갔어요.'],
        answer: '먹고 집에 갔어요.',
        why: 'The first verb is stem + 고. The tense goes on the last verb only.',
        whyTl: 'Stem + 고 sa una, at ang past sa huli lang.',
      },
      {
        kind: 'choice',
        prompt: 'Which word means "but" or "by the way"?',
        options: ['그런데', '그리고', '그거'],
        answer: '그런데',
        why: '그런데 introduces a contrast or a new topic.',
        whyTl: '그런데 = pero / nga pala.',
      },
      {
        kind: 'choice',
        prompt: 'Which word starts a new sentence with "and"?',
        options: ['그리고', '그런데', '그래서'],
        answer: '그리고',
        why: '그리고 means "and" or "and then".',
        whyTl: '그리고 = at.',
      },
    ],
  },
  {
    id: '2.10',
    phase: 2,
    title: 'Can and cannot: -(으)ㄹ 수 있어요',
    ko: '-(으)ㄹ 수 있어요',
    blurb: 'Saying what you are able to do.',
    items: [
      { id: 's.읽을수있어요', korean: '한국어를 읽을 수 있어요.', english: 'I can read Korean.' },
      { id: 's.수영할수있어요', korean: '수영할 수 있어요.', english: 'I can swim.' },
      { id: 's.할수없어요', korean: '할 수 없어요.', english: 'I cannot do it.' },
    ],
    steps: [
      {
        kind: 'teach',
        title: 'Same ending as the future',
        body: [
          'Take the same ㄹ / 을 ending as 거예요, then add 수 있어요 for "can" or 수 없어요 for "cannot".',
          'Vowel stem + ㄹ 수 있어요: 가 → 갈 수 있어요. Consonant stem + 을 수 있어요: 읽 → 읽을 수 있어요.',
        ],
        tl: ['Ang -(으)ㄹ ay pareho sa future. 수 있어요 = "may paraan" = kaya. 수 없어요 = "walang paraan" = hindi kaya. Parang "may magagawa" at "walang magagawa".'],
        tip: 'Ang 수 ay "paraan" o "posibilidad". Ang 있어요/없어요 na natutunan mo sa 1.5 ay bumalik. Kaya ang lahat ng natutunan mo ay nagsasama-sama.',
        remember: '수 있어요 = "may paraan". 수 없어요 = "walang paraan". Kaya at hindi kaya.',
        phrases: [
          { ko: '읽을 수 있어요.', en: 'I can read.', rom: 'ilgeul su isseoyo' },
          { ko: '수영할 수 있어요.', en: 'I can swim.', rom: 'suyeonghal su isseoyo' },
          { ko: '할 수 없어요.', en: 'I cannot do it.', rom: 'hal su eopseoyo' },
        ],
      },
      {
        kind: 'teach',
        title: 'Your goal sentence',
        body: [
          'By now you can say: 저는 한국어를 읽을 수 있어요. "I can read Korean."',
          'That was the goal of Phase 0. Every piece of that sentence is something you have learned.',
        ],
        tl: ['Tingnan mo kung gaano ka na kalayo. 저는 (topic) 한국어를 (object) 읽을 수 있어요 (can read). Lahat ay natutunan mo na.'],
        tip: 'Ngayon, subukang gumawa ng sarili mong pangungusap. Palitan ang 한국어 ng ibang salita na alam mo.',
        remember: 'Ang pangungusap na ito ang patunay na kaya mo. 한국어를 읽을 수 있어요!',
        phrases: [
          { ko: '저는 한국어를 읽을 수 있어요.', en: 'I can read Korean.' },
          { ko: '저는 아직 말할 수 없어요.', en: 'I cannot speak yet.' },
        ],
      },
      {
        kind: 'choice',
        prompt: 'Make "I can read" from 읽다 (stem 읽).',
        options: ['읽을 수 있어요', '읽ㄹ 수 있어요', '읽 수 있어요'],
        answer: '읽을 수 있어요',
        why: '읽 ends in a consonant, so 을 수 있어요.',
        whyTl: 'May batchim ang 읽, kaya 을 수 있어요.',
      },
      {
        kind: 'choice',
        prompt: 'Make "I can go" from 가다.',
        options: ['갈 수 있어요', '가을 수 있어요', '가 수 있어요'],
        answer: '갈 수 있어요',
        why: '가 ends in a vowel, so ㄹ attaches: 갈 수 있어요.',
        whyTl: 'Walang batchim ang 가, kaya ㄹ lang.',
      },
      {
        kind: 'choice',
        prompt: 'What does 할 수 없어요 mean?',
        big: '할 수 없어요',
        options: ['I cannot do it.', 'I can do it.', 'I will do it.'],
        answer: 'I cannot do it.',
        why: '수 없어요 means "cannot".',
        whyTl: '수 없어요 = hindi kaya.',
      },
    ],
  },
];

export const UPCOMING3: { id: string; title: string; ko: string }[] = [];
