import type { Lesson } from './lessons';

type Extra = { tl?: string[]; tip?: string; remember?: string };

/** Taglish / tip / memory hooks layered onto lessons 0.1-0.6. Key: `${lessonId}.${stepIndex}`. */
export const ENRICH: Record<string, Extra> = {
  '0.1.0': {
    tl: ['Sa English, isang line ng letters ang sulat. Sa Korean, parang maliit na bahay ang bawat syllable: isang square block na may consonant at vowel sa loob.'],
    tip: 'Every block starts with a consonant. Kahit vowel lang ang sound, may silent ㅇ sa unahan.',
    remember: 'Isipin mo ang block na parang Lego: laging magkakadikit ang pieces, hindi kailanman nakahiwalay.',
  },
  '0.1.1': {
    tl: ['Kung patayo ang vowel (ㅏ ㅣ), nasa kanan ng consonant. Kung pahiga (ㅗ ㅜ ㅡ), nasa ilalim. Kung may final consonant, nasa pinakababa.'],
    tip: 'Tingnan ang hugis ng vowel muna. Tall = kanan, flat = baba.',
    remember: 'Tall vowels tumatayo sa tabi. Flat vowels humihiga sa ilalim, parang banig.',
  },
  '0.2.0': {
    tl: ['Tatlong simbolo lang ang gamit sa lahat ng vowels: tuldok (langit), pahigang linya (lupa), patayong linya (tao).'],
    tip: 'Hindi mo kailangan ng 21 na memorization. Tatlong shapes, tapos pagsasama-sama lang.',
    remember: 'Langit, lupa, tao. Parang "Heaven, Earth, Man" sa lumang Asian philosophy.',
  },
  '0.2.1': {
    tl: ['Ang tuldok ay nasa gilid ng tao. Sa kanan = ㅏ, sa kaliwa = ㅓ.'],
    tip: 'ㅓ ay hindi "o". Parang "uh" na medyo bilog ang labi.',
    remember: 'ㅏ: araw sa kanan (sumisikat sa silangan) = "ah", bukas na bibig.',
  },
  '0.2.2': {
    tl: ['Ang tuldok ay nasa itaas o ilalim ng lupa. Taas = ㅗ, ilalim = ㅜ.'],
    tip: 'Ang ㅡ ay walang tuldok. Ngumiti ka, tapos sabihin ang "oo". Yan ang ㅡ.',
    remember: 'ㅗ: puno na tumutubo paitaas ("o"). ㅜ: ugat na nasa ilalim ("u").',
  },
  '0.3.0': {
    tl: ['Lima lang ang tunay na base: ㄱ ㄴ ㅁ ㅅ ㅇ. Ang iba ay dagdag na linya sa lima na yan.'],
    tip: 'Kapag nakita mong may bagong consonant, hanapin kung anong base niya. Mabilis kang matututo.',
    remember: 'ㅁ = labi (mouth, M). ㅅ = ngipin (S). ㅇ = lalamunan, bilog na parang "O".',
  },
  '0.3.1': {
    tl: ['Ang ㄹ ay mabilis na tap ng dila, parang "r" sa Spanish o ang gitna ng "butter". Ang ㄱ ㄷ ㅂ ㅈ ay nasa pagitan ng dalawang tunog, kaya parang g/k, d/t, b/p.'],
    tip: 'Huwag mag-alala sa g vs k. Sinasabi mo lang ito nang malambot, at ang tenga mo ang masasanay.',
    remember: 'ㄹ: tingnan ang zigzag, parang dila na tumatalbog.',
  },
  '0.3.2': {
    tl: ['Kapag unang letra ng block ang ㅇ, walang tunog. Placeholder lang. Kapag nasa ilalim, "ng" ito, parang "sing".'],
    tip: 'Kapag nakita mong "아", "이", "오": hindi ito "ng-a". Simpleng "a", "i", "o".',
    remember: 'ㅇ ay zero. Walang laman sa unahan, may "ng" sa dulo.',
  },
  '0.4.0': {
    tl: ['Pag nakita mo ang consonant + ㅏ, sabihin lang ang consonant tapos "ah". Ga, na, da, ma, ba, sa, a, ja, ha.'],
    tip: 'Basahin ang mga ito nang malakas. Ang bibig mo ang matututo, hindi lang ang mata.',
    remember: 'Gumawa ng kanta: ga-na-da-ra-ma-ba-sa. Ito rin ang tradisyonal na Korean alphabet song (가나다라마바사).',
  },
  '0.5.0': {
    tl: ['Dagdagan ng isa pang guhit ang vowel, at may "y" na sa unahan. ㅏ → ㅑ (ya), ㅓ → ㅕ (yeo), ㅗ → ㅛ (yo), ㅜ → ㅠ (yu).'],
    tip: 'Dalawang guhit = "y". Bilangin lang ang guhit para malaman.',
    remember: 'Dalawang tuldok, "y" ang kasama, parang "yo-yo": ㅛ.',
  },
  '0.6.0': {
    tl: ['Hawakan ang palad mo sa harap ng bibig. Sabihin ang "pie": may hangin. Sabihin ang "spy": halos wala. Ang ㅋ ㅌ ㅍ ㅊ ay yung may hangin.'],
    tip: 'Kapag may dagdag na guhit, dagdag na hangin: ㄱ→ㅋ, ㄷ→ㅌ, ㅈ→ㅊ.',
    remember: 'Dagdag na guhit = dagdag na buga ng hangin, parang may dagdag na pagbuga.',
  },
};

export const MORE: Lesson[] = [
  {
    id: '0.7',
    phase: 0,
    title: 'Tense consonants',
    ko: '된소리',
    blurb: 'Doubled letters, tight throat, no air.',
    items: [
      { id: 'c.ㄲ', korean: 'ㄲ', english: 'kk (tight)' },
      { id: 'c.ㄸ', korean: 'ㄸ', english: 'tt (tight)' },
      { id: 'c.ㅃ', korean: 'ㅃ', english: 'pp (tight)' },
      { id: 'c.ㅆ', korean: 'ㅆ', english: 'ss (tight)' },
      { id: 'c.ㅉ', korean: 'ㅉ', english: 'jj (tight)' },
      { id: 'w.아빠', korean: '아빠', english: 'dad' },
      { id: 'w.오빠', korean: '오빠', english: 'older brother (said by a woman)' },
    ],
    steps: [
      {
        kind: 'teach',
        title: 'Double the letter, tighten the throat',
        body: [
          'Write a consonant twice and you get its tense version: ㄲ ㄸ ㅃ ㅆ ㅉ. The sound is short and tight, with no puff of air.',
          'So Korean has three flavours of one sound: soft ㅂ, breathy ㅍ, and tight ㅃ.',
        ],
        tl: ['Kapag doble ang letra, mahigpit at diretso ang tunog. Parang pinipigilan mo ang lalamunan bago ilabas, tapos walang hangin.'],
        tip: 'Hawakan ang lalamunan mo habang sinasabi ang ㅃ. Dapat parang naninigas ito, hindi lumalabas ang hangin sa palad.',
        remember: 'Doble = diin. Parang "PP" sa "PPAP!" na biglang putok at walang hangin.',
        glyphs: [
          { ch: 'ㄲ', sub: 'kk' },
          { ch: 'ㄸ', sub: 'tt' },
          { ch: 'ㅃ', sub: 'pp' },
          { ch: 'ㅆ', sub: 'ss' },
          { ch: 'ㅉ', sub: 'jj' },
        ],
      },
      {
        kind: 'teach',
        title: 'Words you already know',
        body: ['You have probably heard these in K-dramas and songs.'],
        tl: ['Narinig mo na ito sa K-drama. Ang "oppa" ay ㅗ + ㅃ + ㅏ, kaya tight ang "pp" at hindi "opa".'],
        tip: 'Ang 아빠 ay galing sa "papa". Madali, di ba?',
        remember: 'Doble ang P sa oppa dahil mahigpit ang labi mo sa gitna ng salita.',
        phrases: [
          { ko: '아빠', en: 'dad', rom: 'appa' },
          { ko: '오빠', en: 'older brother (a woman says this)', rom: 'oppa' },
        ],
      },
      {
        kind: 'choice',
        prompt: 'Which letter is the tense version of ㅂ?',
        options: ['ㅍ', 'ㅃ', 'ㅁ'],
        answer: 'ㅃ',
        why: 'ㅃ is ㅂ doubled. ㅍ is the breathy one.',
        whyTl: 'Tama. ㅃ ay doble ng ㅂ. Ang ㅍ ay yung may hangin.',
      },
      {
        kind: 'choice',
        prompt: 'Listen. Which syllable?',
        speak: '빠',
        options: ['바', '파', '빠'],
        answer: '빠',
        why: '빠 is the tight "ppa". 바 is soft and 파 is puffy.',
        whyTl: 'Ang 빠 ay mahigpit na "ppa". Ang 바 ay malambot, ang 파 ay may hangin.',
      },
      {
        kind: 'build',
        prompt: 'Build "ssa".',
        speak: '싸',
        initials: ['ㅅ', 'ㅆ', 'ㅈ', 'ㅉ'],
        vowels: ['ㅏ', 'ㅓ', 'ㅗ'],
        target: '싸',
        why: 'ㅆ + ㅏ = 싸.',
        whyTl: 'ㅆ + ㅏ = 싸. Doble ang ㅅ.',
      },
      {
        kind: 'choice',
        prompt: 'How do you read 아빠?',
        big: '아빠',
        options: ['aba', 'appa', 'apa'],
        answer: 'appa',
        why: '아 is "a", 빠 is tight "ppa".',
        whyTl: '아 = "a", 빠 = tight "ppa". Kaya "appa".',
      },
    ],
  },
  {
    id: '0.8',
    phase: 0,
    title: 'Compound vowels',
    ko: '복합 모음',
    blurb: 'Two vowels glued into one sound.',
    items: [
      { id: 'v.ㅐ', korean: '애', english: 'ae' },
      { id: 'v.ㅔ', korean: '에', english: 'e' },
      { id: 'v.ㅘ', korean: '와', english: 'wa' },
      { id: 'v.ㅝ', korean: '워', english: 'wo' },
      { id: 'v.ㅟ', korean: '위', english: 'wi' },
      { id: 'v.ㅢ', korean: '의', english: 'ui' },
      { id: 'w.개', korean: '개', english: 'dog' },
      { id: 'w.사과', korean: '사과', english: 'apple' },
    ],
    steps: [
      {
        kind: 'teach',
        title: 'ㅐ and ㅔ',
        body: [
          'ㅐ and ㅔ are written differently but pronounced almost identically by most speakers today: a plain "eh".',
          'You will rarely mix them up when reading. You only need to be careful when spelling.',
        ],
        tl: ['Magkaiba ang itsura pero halos pareho ang tunog: "eh". Hindi mo kailangang pagtalunan ang pronunciation. Sa pagbabaybay lang mahalaga.'],
        tip: 'Basa muna, spelling mamaya. Memorize ang common words na 개 (aso), 네 (oo).',
        remember: 'ㅐ ay may dalawang patayong linya at medyo siksik, parang "ae". ㅔ ay mas maluwag, "e".',
        glyphs: [
          { ch: 'ㅐ', sub: 'ae' },
          { ch: 'ㅔ', sub: 'e' },
        ],
      },
      {
        kind: 'teach',
        title: 'W-vowels: ㅗ or ㅜ + another vowel',
        body: [
          'Start with ㅗ or ㅜ and slide into the next vowel quickly. ㅗ+ㅏ = ㅘ (wa). ㅜ+ㅓ = ㅝ (wo). ㅜ+ㅣ = ㅟ (wi).',
          'ㅢ is ㅡ + ㅣ. Say "eu" then "ee" fast: "ui".',
        ],
        tl: ['Pinagdikit lang ang dalawang vowels: ㅗ + ㅏ = ㅘ. Basahin mo nang mabilis, parang "o-a" na nagiging "wa".'],
        tip: 'Hindi mo kailangang tandaan ang bawat isa. Hatiin mo lang ang vowel at basahin ang mga piraso.',
        remember: 'Ang ㅘ ay parang "wow": ㅗ + ㅏ = wa.',
        glyphs: [
          { ch: 'ㅘ', sub: 'wa' },
          { ch: 'ㅝ', sub: 'wo' },
          { ch: 'ㅟ', sub: 'wi' },
          { ch: 'ㅢ', sub: 'ui' },
        ],
      },
      {
        kind: 'teach',
        title: 'Real words',
        body: ['Read them using the pieces.'],
        tl: ['Basahin sa piraso: 사 (sa) + 과 (gwa) = sagwa. Huwag bilisan, hatiin muna.'],
        tip: 'Ang 의 ay may tatlong tunog depende sa gamit, pero "ui" ang pangunahing basa.',
        remember: 'Ang 사과 ay "sagwa" (apple). May kasabihan: "sorry" sa Korean ay 사과 din, kaya parang tumatanggap ka ng apple bilang paghingi ng tawad.',
        phrases: [
          { ko: '개', en: 'dog', rom: 'gae' },
          { ko: '사과', en: 'apple', rom: 'sagwa' },
          { ko: '의사', en: 'doctor', rom: 'uisa' },
          { ko: '회사', en: 'company', rom: 'hoesa' },
        ],
      },
      {
        kind: 'choice',
        prompt: 'Which vowel is "wa"?',
        options: ['ㅘ', 'ㅐ', 'ㅢ'],
        answer: 'ㅘ',
        why: 'ㅗ + ㅏ = ㅘ.',
        whyTl: 'ㅗ + ㅏ = ㅘ. Wa!',
      },
      {
        kind: 'build',
        prompt: 'Build "wo" with the silent ㅇ.',
        speak: '워',
        initials: ['ㅇ', 'ㄱ', 'ㅁ'],
        vowels: ['ㅘ', 'ㅝ', 'ㅟ', 'ㅢ'],
        target: '워',
        why: 'ㅇ + ㅝ = 워.',
        whyTl: 'ㅇ + ㅝ = 워. Ang ㅇ ay silent placeholder.',
      },
      {
        kind: 'choice',
        prompt: 'How do you read 의사?',
        big: '의사',
        options: ['uisa', 'euisa', 'isa'],
        answer: 'uisa',
        why: 'ㅢ is "ui", ㅅ + ㅏ is "sa".',
        whyTl: 'ㅢ = "ui", 사 = "sa". 의사 = doktor.',
      },
    ],
  },
  {
    id: '0.9',
    phase: 0,
    title: 'Batchim: final consonants',
    ko: '받침',
    blurb: 'Fourteen letters, only seven sounds.',
    items: [
      { id: 'w.밥', korean: '밥', english: 'rice / a meal' },
      { id: 'w.물', korean: '물', english: 'water' },
      { id: 'w.집', korean: '집', english: 'house' },
      { id: 'w.책', korean: '책', english: 'book' },
      { id: 'w.꽃', korean: '꽃', english: 'flower' },
      { id: 'w.한국', korean: '한국', english: 'Korea' },
    ],
    steps: [
      {
        kind: 'teach',
        title: 'The floor of the block',
        body: [
          'A consonant at the bottom of a block is called batchim (받침, "support"). It closes the syllable.',
          'Many letters can sit there, but they collapse into just seven sounds: k, n, t, l, m, p, ng.',
        ],
        tl: ['Ang batchim ay consonant sa ibaba ng block. Kahit maraming letra, pito lang ang tunog sa dulo: k, n, t, l, m, p, ng.'],
        tip: 'Sa batchim, huwag ilabas ang hangin. Itigil mo lang ang bibig o dila sa posisyon, parang "unreleased" na tunog.',
        remember: 'Parang sa Tagalog: "tak" o "sap". Pinipigilan mo ang dulo, hindi mo na tinatapos ang tunog.',
        glyphs: [
          { ch: 'ㄱ', sub: 'k' },
          { ch: 'ㄴ', sub: 'n' },
          { ch: 'ㄷ', sub: 't' },
          { ch: 'ㄹ', sub: 'l' },
          { ch: 'ㅁ', sub: 'm' },
          { ch: 'ㅂ', sub: 'p' },
          { ch: 'ㅇ', sub: 'ng' },
        ],
      },
      {
        kind: 'teach',
        title: 'Look-alikes share a sound',
        body: [
          'ㄱ ㅋ ㄲ all sound like "k" at the bottom.',
          'ㄷ ㅅ ㅆ ㅈ ㅊ ㅌ ㅎ all sound like "t".',
          'ㅂ ㅍ all sound like "p".',
        ],
        tl: ['Sa ilalim ng block, pare-pareho lang ang tunog ng magkakamag-anak na letra. Kaya 꽃 (kkot), 옷 (ot), 낮 (nat) ay lahat nagtatapos sa "t".'],
        tip: 'Hindi mo kailangang memorize ang bawat letra. Alamin lang ang pamilya: K family, T family, P family.',
        remember: 'K family: ㄱ ㅋ ㄲ. P family: ㅂ ㅍ. T family: lahat ng iba. Tatlong angkan.',
        phrases: [
          { ko: '밥', en: 'rice / a meal', rom: 'bap' },
          { ko: '꽃', en: 'flower', rom: 'kkot' },
          { ko: '책', en: 'book', rom: 'chaek' },
          { ko: '한국', en: 'Korea', rom: 'hanguk' },
        ],
      },
      {
        kind: 'choice',
        prompt: 'How do you read 물?',
        big: '물',
        options: ['mul', 'mur', 'mun'],
        answer: 'mul',
        why: 'ㅁ + ㅜ + ㄹ = mul. At the bottom, ㄹ sounds like "l".',
        whyTl: 'ㅁ + ㅜ + ㄹ = "mul". Ang ㄹ sa ilalim ay "l".',
      },
      {
        kind: 'choice',
        prompt: 'The batchim in 꽃 is ㅊ. Which sound does it make?',
        big: '꽃',
        options: ['ch', 't', 'k'],
        answer: 't',
        why: 'ㅊ is in the "t" family at the bottom: kkot.',
        whyTl: 'Ang ㅊ sa ilalim ay "t", kaya "kkot".',
      },
      {
        kind: 'build',
        prompt: 'Build "jip" (house).',
        speak: '집',
        initials: ['ㅈ', 'ㅅ', 'ㅊ'],
        vowels: ['ㅏ', 'ㅣ', 'ㅜ'],
        finals: ['ㄱ', 'ㄴ', 'ㅁ', 'ㅂ'],
        target: '집',
        why: 'ㅈ + ㅣ + ㅂ = 집.',
        whyTl: 'ㅈ + ㅣ + ㅂ = 집, "jip".',
      },
      {
        kind: 'choice',
        prompt: 'Listen. Which word?',
        speak: '밥',
        options: ['밤', '밥', '반'],
        answer: '밥',
        why: '밥 ends in ㅂ ("p").',
        whyTl: 'Ang 밥 ay nagtatapos sa "p". Ang 밤 ay "m", ang 반 ay "n".',
      },
    ],
  },
  {
    id: '0.10',
    phase: 0,
    title: 'Reading real words',
    ko: '단어 읽기',
    blurb: 'Put everything together.',
    items: [
      { id: 'w.김치', korean: '김치', english: 'kimchi' },
      { id: 'w.커피', korean: '커피', english: 'coffee' },
      { id: 'w.학교', korean: '학교', english: 'school' },
      { id: 'w.서울', korean: '서울', english: 'Seoul' },
      { id: 'w.사랑', korean: '사랑', english: 'love' },
      { id: 'w.가수', korean: '가수', english: 'singer' },
    ],
    steps: [
      {
        kind: 'teach',
        title: 'Read one block at a time',
        body: [
          'To read any Korean word, take it block by block. Split each block into consonant, vowel and final, say it, then glue the blocks together.',
        ],
        tl: ['Hatiin sa blocks, basahin ang bawat block, tapos pagdikitin. Walang magic.'],
        tip: 'Basahin mo nang malakas, kahit mabagal. Ang bilis ay darating mamaya.',
        remember: 'Parang paghahati ng Tagalog sa pantig: ka-pi, pa-ra-an. Pantig-pantig lang.',
        phrases: [
          { ko: '김치', en: 'kimchi', rom: 'gim-chi' },
          { ko: '커피', en: 'coffee', rom: 'keo-pi' },
          { ko: '학교', en: 'school', rom: 'hak-gyo' },
          { ko: '서울', en: 'Seoul', rom: 'seo-ul' },
        ],
      },
      {
        kind: 'teach',
        title: 'Loanwords are your friend',
        body: ['Many Korean words are English sounds written in Hangul. If you can read Hangul, you already know them.'],
        tl: ['May mga salitang hiram sa English na isinulat sa Hangul. Kapag nabasa mo, alam mo na agad ang ibig sabihin: 커피 = coffee.'],
        tip: 'Subukang basahin ang mga signboard o menu. Nakakagulat kung ilan ang alam mo na.',
        remember: '커피 = "keo-pi" = coffee. Basahin mo nang malakas at lalabas ang English.',
        phrases: [
          { ko: '커피', en: 'coffee', rom: 'keopi' },
          { ko: '버스', en: 'bus', rom: 'beoseu' },
          { ko: '호텔', en: 'hotel', rom: 'hotel' },
          { ko: '아이스크림', en: 'ice cream', rom: 'aiseukeurim' },
        ],
      },
      {
        kind: 'choice',
        prompt: 'What does this say?',
        big: '학교',
        options: ['hakgyo', 'hagio', 'hakkyo'],
        answer: 'hakgyo',
        why: '학 = ㅎ + ㅏ + ㄱ (hak). 교 = ㄱ + ㅛ (gyo).',
        whyTl: '학 = "hak", 교 = "gyo". Magkasama: "hakgyo", ibig sabihin school.',
      },
      {
        kind: 'choice',
        prompt: 'Listen. Which word?',
        speak: '김치',
        options: ['김치', '김밥', '감자'],
        answer: '김치',
        why: '김치 is gim-chi.',
        whyTl: 'Ang 김치 ay gim-chi, yung sikat na maasim na gulay.',
      },
      {
        kind: 'choice',
        prompt: 'What does 커피 mean?',
        big: '커피',
        options: ['coffee', 'copy', 'coffin'],
        answer: 'coffee',
        why: 'ㅋ + ㅓ = keo, ㅍ + ㅣ = pi. "Keopi" sounds like coffee.',
        whyTl: 'Basahin: "keo-pi". Medyo nakakahawig ng "coffee", di ba?',
      },
      {
        kind: 'choice',
        prompt: 'How do you read 서울?',
        big: '서울',
        options: ['seoul', 'sool', 'suul'],
        answer: 'seoul',
        why: '서 = seo, 울 = ul. Together "seoul".',
        whyTl: '서 = seo, 울 = ul. Seoul!',
      },
    ],
  },
  {
    id: '0.11',
    phase: 0,
    title: 'Typing Korean',
    ko: '한글 타자',
    blurb: 'The 2-set keyboard layout.',
    items: [
      { id: 'k.ㅎ', korean: 'ㅎ', english: 'key G' },
      { id: 'k.ㅏ', korean: 'ㅏ', english: 'key K' },
      { id: 'k.ㄴ', korean: 'ㄴ', english: 'key S' },
      { id: 'k.ㄱ', korean: 'ㄱ', english: 'key R' },
    ],
    steps: [
      {
        kind: 'teach',
        title: 'Consonants on the left, vowels on the right',
        body: [
          'Korean keyboards use the 2-set layout (두벌식). Consonants are on the left hand side of the keyboard, vowels on the right.',
          'You type the letters in order, and the computer assembles the blocks for you: ㅎ + ㅏ + ㄴ = 한.',
        ],
        tl: ['Sa kaliwa ang consonants, sa kanan ang vowels. Isa-isa mong tatayp ang letra, at ang computer na ang bubuo ng block.'],
        tip: 'Add Korean as a language in Windows or your phone settings. Walang kailangang bilhin na keyboard.',
        remember: 'Consonants kaliwa, vowels kanan, parang pag-type ng "ka" sa pagitan ng dalawang kamay.',
        glyphs: [
          { ch: 'ㅎ', sub: 'G' },
          { ch: 'ㅏ', sub: 'K' },
          { ch: 'ㄴ', sub: 'S' },
        ],
      },
      {
        kind: 'teach',
        title: 'The home row',
        body: [
          'On the middle row, the left hand has ㅁ ㄴ ㅇ ㄹ ㅎ (A S D F G) and the right hand has ㅗ ㅓ ㅏ ㅣ (H J K L).',
          'Shift gives the tense or double versions: Shift + R = ㄲ, Shift + Q = ㅃ.',
        ],
        tl: ['Sa home row: ㅁ ㄴ ㅇ ㄹ ㅎ sa kaliwa, ㅗ ㅓ ㅏ ㅣ sa kanan. Pindutin ang Shift para sa doble, halimbawa Shift + R = ㄲ.'],
        tip: 'Practice by typing your own name phonetically. It is more fun than random drills.',
        remember: 'A S D F G = ㅁ ㄴ ㅇ ㄹ ㅎ. Parang "ASDFG" lang, kaya madaling hanapin ang vowel group sa kanan: HJKL.',
        glyphs: [
          { ch: 'ㅁ', sub: 'A' },
          { ch: 'ㄴ', sub: 'S' },
          { ch: 'ㅇ', sub: 'D' },
          { ch: 'ㄹ', sub: 'F' },
          { ch: 'ㅎ', sub: 'G' },
        ],
      },
      {
        kind: 'choice',
        prompt: 'Which key types ㅎ?',
        options: ['G', 'H', 'K'],
        answer: 'G',
        why: 'ㅎ is on G. H is ㅗ and K is ㅏ.',
        whyTl: 'Ang ㅎ ay nasa G. Ang H ay ㅗ, ang K ay ㅏ.',
      },
      {
        kind: 'choice',
        prompt: 'Which key types ㅏ?',
        options: ['K', 'J', 'S'],
        answer: 'K',
        why: 'ㅏ is on K. J is ㅓ.',
        whyTl: 'Ang ㅏ ay nasa K. Ang J ay ㅓ.',
      },
      {
        kind: 'choice',
        prompt: 'To type 한, which keys do you press in order?',
        big: '한',
        options: ['G, K, S', 'S, K, G', 'K, G, S'],
        answer: 'G, K, S',
        why: 'ㅎ (G) + ㅏ (K) + ㄴ (S) = 한.',
        whyTl: 'ㅎ (G) + ㅏ (K) + ㄴ (S) = 한. Consonant, vowel, final.',
      },
    ],
  },

  {
    id: '1.1',
    phase: 1,
    title: 'Greetings and thanks',
    ko: '인사',
    blurb: 'The first words you actually use.',
    items: [
      { id: 'p.안녕하세요', korean: '안녕하세요', english: 'hello' },
      { id: 'p.감사합니다', korean: '감사합니다', english: 'thank you' },
      { id: 'p.죄송합니다', korean: '죄송합니다', english: 'I am sorry (formal)' },
      { id: 'p.네', korean: '네', english: 'yes' },
      { id: 'p.아니요', korean: '아니요', english: 'no' },
    ],
    steps: [
      {
        kind: 'teach',
        title: 'Hello in every situation',
        body: [
          '안녕하세요 works at any time of day, with anyone you should be polite to: shop staff, teachers, strangers.',
          'It literally asks, "Are you at peace?" You answer by saying it back.',
        ],
        tl: ['Isang "hello" lang para sa lahat ng oras: umaga, tanghali, gabi. Para itong "kumusta po". Sabihin mo rin pabalik.'],
        tip: 'Yumuko nang bahagya habang sinasabi. Ito ang karaniwang gawi sa Korea.',
        remember: '안녕 ay parang "annyeong", at sa Tagalog parang "anong-?" (Anong balita?). Tunog lang, pero nakakatulong.',
        phrases: [
          { ko: '안녕하세요', en: 'hello', rom: 'annyeonghaseyo' },
          { ko: '안녕히 가세요', en: 'goodbye (to someone leaving)', rom: 'annyeonghi gaseyo' },
          { ko: '안녕히 계세요', en: 'goodbye (to someone staying)', rom: 'annyeonghi gyeseyo' },
        ],
      },
      {
        kind: 'teach',
        title: 'Thank you, sorry, yes, no',
        body: [
          '감사합니다 is polite thanks. 죄송합니다 is a formal sorry. 네 is yes and 아니요 is no.',
        ],
        tl: ['Ang 감사합니다 ay "salamat po". Ang 죄송합니다 ay "pasensya po". 네 = oo, 아니요 = hindi.'],
        tip: 'Ang 네 ay maaaring mangahulugang "oo, nakikinig ako" at hindi laging "agree". Madalas itong ginagamit bilang "ah, sige".',
        remember: '감사 ay "gamsa", parang "gamsa-hamnida" ay mahaba, pero isipin mo "gamsa" = "salamat".',
        phrases: [
          { ko: '감사합니다', en: 'thank you', rom: 'gamsahamnida' },
          { ko: '죄송합니다', en: 'I am sorry', rom: 'joesonghamnida' },
          { ko: '네', en: 'yes', rom: 'ne' },
          { ko: '아니요', en: 'no', rom: 'aniyo' },
        ],
      },
      {
        kind: 'choice',
        prompt: 'What does 감사합니다 mean?',
        big: '감사합니다',
        options: ['Thank you', 'Goodbye', 'I am sorry'],
        answer: 'Thank you',
        why: '감사 means gratitude. 감사합니다 is polite thanks.',
        whyTl: 'Ang 감사합니다 ay "salamat po".',
      },
      {
        kind: 'choice',
        prompt: 'You are leaving a shop. What do you say to the staff who stay?',
        options: ['안녕히 계세요', '안녕히 가세요', '감사합니다'],
        answer: '안녕히 계세요',
        why: '계세요 means "stay". You are going; they are staying.',
        whyTl: 'Ikaw ang aalis, sila ang mananatili, kaya 계세요 (stay). Kapag sila ang aalis, 가세요 (go).',
      },
      {
        kind: 'choice',
        prompt: 'What does 아니요 mean?',
        big: '아니요',
        options: ['yes', 'no', 'hello'],
        answer: 'no',
        why: '아니요 is a polite no.',
        whyTl: '아니요 = hindi (polite).',
      },
    ],
  },
  {
    id: '1.2',
    phase: 1,
    title: 'I am X: -이에요 / -예요',
    ko: '이에요 / 예요',
    blurb: 'Your first full sentence.',
    items: [
      { id: 's.저는학생이에요', korean: '저는 학생이에요.', english: 'I am a student.' },
      { id: 's.의사예요', korean: '의사예요.', english: 'I am a doctor.' },
      { id: 'w.저', korean: '저', english: 'I (polite)' },
      { id: 'w.학생', korean: '학생', english: 'student' },
    ],
    steps: [
      {
        kind: 'teach',
        title: 'A noun plus "to be"',
        body: [
          'Korean has no separate word for "am / is / are". You attach it to the end of a noun: 학생 (student) + 이에요 = 학생이에요, "I am a student".',
          'The verb always comes last. We will build on this idea every lesson.',
        ],
        tl: ['Walang hiwalay na "ay" o "ako ay". Idinudugtong lang sa dulo ng noun: 학생 + 이에요 = "estudyante ako". Sa dulo ng pangungusap laging ang verb.'],
        tip: 'Sa Korean, madalas tinatanggal ang "ako" kung halata naman sa konteksto. 학생이에요 lang ay puwede na.',
        remember: 'Parang Tagalog na nagtatapos ng pangungusap sa "ako" o "ka": 학생이에요 ≈ "estudyante nga".',
        phrases: [{ ko: '저는 학생이에요.', en: 'I am a student.' }],
      },
      {
        kind: 'teach',
        title: '이에요 or 예요?',
        body: [
          'If the noun ends in a consonant (batchim), use 이에요: 학생이에요.',
          'If it ends in a vowel, use 예요: 의사예요, 가수예요.',
        ],
        tl: ['Tingnan ang huling letra. May batchim (nasa ilalim)? 이에요. Walang batchim (vowel lang)? 예요.'],
        tip: 'Puwede mong sabihin nang mabilis dahil magkapareho ang tunog nila. Nagbabago lang ang spelling.',
        remember: 'Consonant + 이에요, vowel + 예요. "이" ay parang "i" para sa "in" (may batchim).',
        phrases: [
          { ko: '학생이에요.', en: 'I am a student.', rom: 'haksaeng-ieyo' },
          { ko: '의사예요.', en: 'I am a doctor.', rom: 'uisa-yeyo' },
          { ko: '가수예요.', en: 'I am a singer.', rom: 'gasu-yeyo' },
        ],
      },
      {
        kind: 'choice',
        prompt: 'Which ending fits 학생 (ends in a consonant)?',
        options: ['이에요', '예요'],
        answer: '이에요',
        why: '학생 ends in ㅇ batchim, so it takes 이에요.',
        whyTl: 'May batchim ang 학생 (ㅇ), kaya 이에요.',
      },
      {
        kind: 'choice',
        prompt: 'Which ending fits 가수 (ends in a vowel)?',
        options: ['이에요', '예요'],
        answer: '예요',
        why: '수 ends in a vowel, so it takes 예요.',
        whyTl: 'Walang batchim ang 가수, kaya 예요.',
      },
      {
        kind: 'choice',
        prompt: 'What does 의사예요 mean?',
        big: '의사예요',
        options: ['I am a doctor.', 'I am a student.', 'I am a singer.'],
        answer: 'I am a doctor.',
        why: '의사 = doctor, 예요 = am.',
        whyTl: '의사 = doktor, 예요 = ako ay.',
      },
    ],
  },
  {
    id: '1.3',
    phase: 1,
    title: 'Topic marker: 은 / 는',
    ko: '은 / 는',
    blurb: 'Pointing at what you are talking about.',
    items: [
      { id: 's.저는미국사람이에요', korean: '저는 미국 사람이에요.', english: 'I am American.' },
      { id: 's.저는필리핀사람이에요', korean: '저는 필리핀 사람이에요.', english: 'I am Filipino.' },
      { id: 'w.사람', korean: '사람', english: 'person' },
    ],
    steps: [
      {
        kind: 'teach',
        title: 'A tag for the topic',
        body: [
          '은 and 는 mark the topic of the sentence: "As for X...". 저는 means "As for me".',
          'It is not the same as the English word "is". It just says "this is what I am talking about".',
        ],
        tl: ['Ito yung "Ako naman..." o "Pagdating sa akin...". Parang "ang" sa Tagalog, pero mas banayad. Tinuturo nito ang pinag-uusapan.'],
        tip: 'Gamitin ang 저 (polite "I") kapag nagsasalita sa kausap na hindi mo kakilala. Ang 나 ay para sa kaibigan.',
        remember: 'Kapag may batchim: 은. Kapag wala: 는. Tulad ng 이에요/예요.',
        phrases: [
          { ko: '저는 학생이에요.', en: 'I am a student.' },
          { ko: '저는 필리핀 사람이에요.', en: 'I am Filipino.' },
        ],
      },
      {
        kind: 'teach',
        title: '은 or 는?',
        body: [
          'Same rule as before. After a consonant use 은, after a vowel use 는.',
          '저 ends in a vowel, so: 저는. 사람 ends in a consonant, so: 사람은.',
        ],
        tl: ['May batchim = 은, wala = 는. 저 → 저는. 사람 → 사람은.'],
        tip: 'Hindi mo kailangang magmemorize ng list. Sa dami mo ng makikita, kusa na itong lalabas.',
        remember: 'Ang 은 ay "eun" at mukhang may "bukol" sa ilalim (ㄴ). May batchim → 은.',
        phrases: [
          { ko: '저는', en: 'as for me', rom: 'jeo-neun' },
          { ko: '사람은', en: 'as for the person', rom: 'saram-eun' },
        ],
      },
      {
        kind: 'choice',
        prompt: 'Which particle goes after 저 (ends in a vowel)?',
        options: ['은', '는'],
        answer: '는',
        why: '저 has no batchim, so it takes 는.',
        whyTl: 'Walang batchim ang 저, kaya 는.',
      },
      {
        kind: 'choice',
        prompt: 'Which particle goes after 사람 (ends in ㅁ)?',
        options: ['은', '는'],
        answer: '은',
        why: '사람 has batchim ㅁ, so it takes 은.',
        whyTl: 'May batchim ang 사람 (ㅁ), kaya 은.',
      },
      {
        kind: 'choice',
        prompt: 'How do you say "I am Filipino"?',
        options: ['저는 필리핀 사람이에요.', '저은 필리핀 사람이에요.', '저는 필리핀 사람예요.'],
        answer: '저는 필리핀 사람이에요.',
        why: '저는 (vowel) and 사람이에요 (consonant). Both rules at once.',
        whyTl: '저는 (walang batchim → 는) at 사람이에요 (may batchim → 이에요). Dalawang rule, isang sentence.',
      },
    ],
  },
];

export const UPCOMING: { id: string; title: string; ko: string }[] = [];
